### ISSUE TITLE
UI Tooltips on touch devices

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1006]
Our tooltips are currently displayed on a hover state, which isn't a great event for touch devices. Because of this tooltip on hover, touch devices show the tooltip on the first tap, and then trigger action only on the second tap. 

Are we ok with this? Should we find a different solution for tooltips on touch devices (for example, disable them on touch devices altogether)?

**Comment by Pedro719** [comment]
There are a lot of directions we can go with this:
1) Leave the double tap method. Fix the rest of the UX/UI for the mobile and see how users react.
2) Like you mentioned: disabling tooltips all together on touch devices which can work if the user does not need to use them in order to complete tasks on on touch screen devices.
3) create a new interaction for mobile which displays the tooltips in some kind of sliding action. The problem with this is that it's very different behavior from the web/desktop version which can cause users to become confused.
3) Remove the hover interaction entirely on KoBo to access tooltips, which is a drastic change. We can replace it by making the tooltips appear through a right-click and then on mobile have the tooltips appear by having the user touch an icon like "more vert" (material design). I think this would be the best long term solution since hover states are being used less due to responsive design best practices.

**Comment by pmusaraj** [comment]
Superseded by #1272
