### ISSUE TITLE
Automate extracting translatable strings from client code.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#1080]

**Comment by dorey** [comment]
I agree that we need to automate this process. Attached is the latest english `.po` file, which I created through a somewhat manual process that logged existing untranslated strings to the console (in f8ba23 ).

[kpi_djangojs_en.po.txt](https://github.com/kobotoolbox/kpi/files/683470/kpi_djangojs_en.po.txt)

**Comment by dspwj** [comment]
I read the issue kobotoolbox/kpi#1080. I want localize the es6 and js files. But the js file created by javascript_catalog is  django.gettext = function (msgid) { return msgid; }. I find a tag sentence {% if catalog_str %} in django.view.i18n.javascript_catalog. If the  catalog_str == True then the django.gettext return the tranlsation string. But in some html pages the django.gettext = function (msgid) { return msgid; }. How can I get the "catalog_str == True" so that let the django.gettext return the translated string. Thank you very much.

**Comment by tfgbestneal** [comment]
To dorey and esmail,
     Could you tell me how to manual process that logged existing untranslated strings in .es6 files? Thanks a lot.

**Comment by jnm** [comment]
Does this issue aim at something more automated than what's described at https://github.com/kobotoolbox/form-builder-translations?

**Comment by joshuaberetta** [comment]
@JacquelineMorrissette, is this something you've already worked on?

**Comment by JacquelineMorrissette** [comment]
@joshuaberetta The extracting translatable strings was already automated. We have github actions that automate the rest of the process

**Comment by joshuaberetta** [comment]
@JacquelineMorrissette great, thanks 👍
