### ISSUE TITLE
`sync_kobocat_xforms` queue expiration setting doesn't work.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#1131]
Food for thought: is there a way to create an integration test for this?

**Comment by esmail** [comment]
See FlowDock conversation: https://www.flowdock.com/app/kobotoolbox/kobo/threads/JJB3io1D1Tv5wOYSUc_MuMFb6ZN

**Comment by jnm** [comment]
My mistake: I thought there was a problem after seeing many `sync_kobocat_xforms` jobs in the Rabbit queue that should've been expired. The queue itself, however, doesn't discard tasks; it's the workers' responsibility to check whether a task has expired before executing it. Many jobs accumulated in the queue because the [queue-nonspecific `beat`](https://github.com/kobotoolbox/kpi/pull/1068#pullrequestreview-13863709) was running but all `sync_kobocat_xforms` workers were stopped.
