### ISSUE TITLE
Projects added from the legacy system doesn't show in kpi

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1340]
All of the XLS forms uploaded and deployed directly through the legacy projects are not visible in the kpi. For example see the attached images. Image 1 shows a project 'F01_KII_Survey_Americas' uploaded through the legacy system. But it doesn't show in image 2, which is the print screen of kpi ( all deployed projects).

![project_legacy](https://user-images.githubusercontent.com/5639037/27277933-3e0b958a-54e0-11e7-92f2-e1700dbc6b39.png)
![projects_kpi](https://user-images.githubusercontent.com/5639037/27277940-4450de3c-54e0-11e7-8aca-c4df48940a87.png)

**Comment by jnm** [comment]
I think this was caused by `sync_kobocat_xforms` being bogged down prior to the fix for https://github.com/kobotoolbox/kpi/issues/1318 being deployed, but it's hard to verify because user deleted their `F01_KII_Survey_Americas` form.

I don't see any other discrepancies for this account, but please reopen the issue if there are other (current) examples of this problem. In some cases, it may take up to an hour for forms uploaded through the legacy interface (KoBoCAT) to appear in KPI.

![image](https://user-images.githubusercontent.com/2085013/27417402-194f0430-56e2-11e7-82e8-55cb73879a88.png)

**Comment by ferminarellano** [comment]
@jnm can you give some further information on what is supposed to run within an hour? I installed Kobotoolbox on my own server, and migrated some info with ODK Briefcase from humanitarianresponse.info to my own server. Data and form is only visible from KoboCat but not from KPI interface.  It´s been more than 6 hours since I uploaded data to Kobocat with Briefcase. I ran ./manage.py sync_mongo --remongo but no success. 

Can you point me out what must be failing or what process should I trigger?
