### ISSUE TITLE
Form title does not change on redeploy

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1372]
* Leading to asset name getting overwritten by `sync_kobocat_xforms`

**Comment by pmusaraj** [comment]
@jnm @noliveleger while working on #620 I noticed that the Form title still doesn't change on a redeploy. A few users have also mentioned it in our support channel recently.

**Comment by noliveleger** [comment]
@pmusaraj @jnm, I've just taken a look at this:
- Asset versions seems to be a KPI feature. Kobocat doesn't know anything about versions (actually I've found no tables related to KC with XForm version).
- EE asks KC for XForm data.

@jnm What about pushing to KC the latest name of the asset when redeploying it. 
I would add another field `latest_deployed_title` in `logger_xform` table. To keep a trace the name of original form title.
We would be able to expose in the view EE is asking for. If field `latest_deployed_title` is not empty then use it instead of `title`

**Comment by jnm** [comment]
From [flowdock discussion](https://www.flowdock.com/app/kobotoolbox/kobo/threads/VPlmJvy4PRmaNnTeAHWeIGHMx9s): it seems like I neglected to include `title` in the `payload`: https://github.com/kobotoolbox/kpi/blob/50a64f1ce2d5ec1009fdbfefa73adba86a6687e2/kpi/deployment_backends/kobocat_backend.py#L297

**Comment by pmusaraj** [comment]
Closed via PR #1584
