### ISSUE TITLE
HXL feedback

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1479]
- [x] Empty hashtag ie. just hash (#) should not be allowed.
    * Done by Penar
- [x] Also multiple hashes ### should not be allowed.
    * Done by Penar
- [x] # should not be allowed in attributes.
    * Done by Penar
- [x] There are various characters like $ and % etc. that should not be allowed in hashtags
    * Done by Penar
- [x] Hashtags and attributes should be lowercase only for stylistic reasons
    * Done by Penar
- [x] It would be nice to be able to edit the hashtag and attribute rather than delete and recreate but this is not a huge problem.
    * WONTFIX per Penar
- [x] Should custom tags be forced to have the x_ prefix?
    * No, per John
- [x] When downloading, it might be nice to have the option to include the labels, hxl tags or both.
    * John: right now we always export both when HXL is present. With just a "nice to have" request, I'd prefer to leave it as is
- [ ] Exported HXL row has a space preceding each attribute. This is allowed in the standard, but stylistically uncommon.  Consider removing those spaces.
    * John to investigate removing this
- [x] In the download, HXL attributes appear in the order added in the interface.  It might be nice to display a "final hxl tag" in the interface to make it explicit to users how the tag will appear.  This might help encourage emerging informal best practices like #affected+displaced+m rather than #affected+m+displaced
    * John: I don't fully understand this. Besides showing the `+` characters and two separate entry fields, what's the difference between what the form builder shows and what's exported?
    * Penar: I agree, we shouldn't add any additional interface for this. Marking as WONTFIX.
- [ ] ⚠ We need to be able to hashtag metadata columns. For example, if I include “today” in metadata, it would be useful to have it hashtagged as #date+collected (or maybe something user-selectable). Ditto, perhaps, for #date+submitted (_submission), #meta+uuid (_uuid), and #meta+index (_index).
    * John: We currently don't have a settings interface for any metadata questions. Penar and I agree that this would be a large undertaking. Users can set HXL tags for these questions by using XLSForm.
- [ ] ⚠ For location, a single question generates four columns, so the user needs to be able to specify four HXL hashtag specs, typically #geo+lat, #geo+lon, #geo+elev, #geo+accuracy. Almost always, these could be prefilled, because the user would rarely change them (except, perhaps, to distinguish multiple locations in the same row, but that would be a rare edge case).
    * John: @pmusaraj, this also seems like a large undertaking unless we hard-code the attributes
- [ ] For enumerated values with multiselect, the results include a column for the human-readable text, and then separate columns with boolean flags for each option. For now, it would be best not to apply the hashtag to the boolean columns, to avoid confusion in processing (just leave it blank).
    * John to investigate making this change in formpack
- [x] When multiple selections are allowed, it would be useful to add +list to the attributes for the HXL hashtag.
    * WONTFIX per John: let the user do it if they want
- [x] When entering tags it would be nice not have to press enter for it appear.  Many times I typed out the tag, clicked away and it disappeared.
    * WONTFIX per Penar
- [ ] ~~Multi-select gives the same tag for every answer.  It would be great to unique attributes on each answer~~
    * John will go with earlier approach of including the tag only in the first exported column for select_multiple questions
- [x] The HXL tags do not appear in the CSV and XLS legacy downloads
    * WONTFIX per John
- [ ] ~~Auto-generated fields do not have HXL tags~~
    * John: assuming this the same as the metadata questions mentioned earlier

## Non-requests

* In future, it would be great for HXL hashtags which have implied types and for attributes that set type (like +num) if that was then reflected in the type setting of Kobo (ie. so that these cannot be in conflict). More needs to be done on HDX side before this is possible.
* Is it worth having discussion on how HXL dataset can more readily feed into analysis scripts or visualise like we have done before and what requirements may need to be added (eg. identifying multi-select over multiple columns)

**Comment by pmusaraj** [comment]
@jnm answers to a few items from the list: 

- for metadata columns, you are correct, this would be a large undertaking. We currently only have checkboxes for each metadata item, no specific settings for each. 
- location (geo) questions: this would also be a large undertaking, yes. It's true that hard-coding would be fairly easy, but, we can't hardcode for all forms, because plenty of users don't use HXL tags, and I don't think it's a good thing to do to hardcode extra data in their exports.

**Comment by jnm** [comment]
Thanks @pmusaraj. I've marked these with ⚠ above, as I don't think we can complete them in a reasonable amount of time given the rest of our workload.

**Comment by jnm** [comment]
Also, I noted above that HXL for metadata questions can already be set using XLSForm.

For the location questions, if UNHCR is adamant, then I would offer to hard-code `+lat`, `+lon`, etc. in our exports when a HXL tag is present on the GPS question. Example export header, given a GPS question called `label` with the HXL tag `#tag` would look like:

    label | _label_latitude | _label_longitude |  _label_altitude | _label_precision
    #tag  | #tag+lat        | #tag+lon         |  #tag+elev       | #tag+accuracy   

This would be simple concatenation, so if the user tagged the GPS question with `#tag+attr`, then the split columns would show `#tag+attr+lat`, `#tag+attr+lon`, ...

Don't forget: confirm that the HXL standard actually matches the location attributes provided in the UNHCR feedback

**Comment by tinok** [comment]
I suggest a small change on the altitude tag: We should append `elevation+m` instead of `elev` as per https://tools.humdata.org/examples/hxl/. Sent email to confirm but `elev` is most likely wrong.

**Comment by davidmegginson** [comment]
_For location, a single question generates four columns, so the user needs to be able to specify four HXL hashtag specs, typically #geo+lat, #geo+lon, #geo+elev, #geo+accuracy. Almost always, these could be prefilled, because the user would rarely change them (except, perhaps, to distinguish multiple locations in the same row, but that would be a rare edge case)._
- _John: @pmusaraj, this also seems like a large undertaking unless we hard-code the attributes_

I think it's safe to hard-code in this case. The recommended attributes are +lat, +lon, and +elevation (though some users have also used +elev in the past).

**Comment by davidmegginson** [comment]
_In the download, HXL attributes appear in the order added in the interface. It might be nice to display a "final hxl tag" in the interface to make it explicit to users how the tag will appear. This might help encourage emerging informal best practices like #affected+displaced+m rather than #affected+m+displaced_

I don't think it's necessary to allow the user to determine the order, but it might be nice to sort the attributes in the generated data (e.g. always #affected+displaced+m). That would make diffs easier when using naive, non-HXL-aware software. This is **not** a requirement of the HXL standard, though.

**Comment by davidmegginson** [comment]
_We need to be able to hashtag metadata columns. For example, if I include “today” in metadata, it would be useful to have it hashtagged as #date+collected (or maybe something user-selectable). Ditto, perhaps, for #date+submitted (_submission), #meta+uuid (_uuid), and #meta+index (_index)._
- _John: We currently don't have a settings interface for any metadata questions. Penar and I agree that this would be a large undertaking. Users can set HXL tags for these questions by using XLSForm._

I don't think any interface is necessary, but would it hardcode these for HXL export?

**Comment by tinok** [comment]
I agree that if users want to use `today` with the hxl tag `#date+collected ` they can do this via the XLSForm import. I would strongly suspect most users who use HXL tags also use XLSForm as their primary formbuilding tool and only use the formbuilder for small edits.

**Comment by tinok** [comment]
Closing. Remaining items will be added as separate issues.
