### ISSUE TITLE
submission count differs from data table and exports

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1541]
Example of this can be found with username: plestari project name: sosek_ntb_2018

[removed user data]

**Comment by noliveleger** [comment]
This bug is related to this [KC issue](https://github.com/kobotoolbox/kobocat/issues/416). 
JS variables have been modified to be compliant with the backend.

**Comment by noliveleger** [comment]
When reviewed and merged, we'll need to resync mongo to retrieve missing data.

**Comment by jnm** [comment]
General missing data issues on kf/kc.kobotoolbox.org should've been resolved once `sync_mongo --remongo` finished on Feb 2 @ 1:10 AM EST: https://www.flowdock.com/app/kobotoolbox/support/messages/366036.

The underlying cause, which forced us to temporarily roll back KC's support for record validation, was fixed in https://github.com/kobotoolbox/kobocat/pull/417, and the complementary KPI fix is https://github.com/kobotoolbox/kpi/pull/1549
