### ISSUE TITLE
Report view fails with 500 error

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1624]
Instead of loading the report the user sees `This report cannot be loaded. INTERNAL SERVER ERROR: <h1>Server Error (500)</h1>` 

This happens to mostly old forms with projects on PROD with user `drc_14`, so it's possible they share some underlying problem with the form definition.

**Comment by pmusaraj** [comment]
I'm going to ping @jnm here because the 500 errors are generally coming from the backend.

**Comment by pmusaraj** [comment]
See #1548

**Comment by noliveleger** [comment]
For reference: `kpi-issue-1624` branch in `FormPack` has some fixes related to this bug.

**Comment by pmusaraj** [comment]
Yes, the issue is introduced by a problem with translations in the form definition. In the initial form, there was an unnamed language with no labels for either questions or choices, and the report would fail because of this. Olivier did some work to fix this in formpack, but it was inconclusive. 

However, updating the form definition to remove the empty language column and then redeploying that fixes the issue as well.

**Comment by noliveleger** [comment]
@pmusaraj @tinok. Finally `kpi-issue-1624` branch in FormPack does fix this issue. A [PR](https://github.com/kobotoolbox/formpack/pull/168) has been created for it.

**Comment by alnf** [comment]
@jnm I have this issue currently, does it mean I need to change smth in my form?

**Comment by jnm** [comment]
@alnf it's hard to say. If you're using one of our instances, you should use the support bubble to contact us and tell us which form is having trouble. If you're running your own instance, could you get more info about the exception? [Turn on Django debugging for KPI](https://github.com/kobotoolbox/kobo-docker/blob/2fff8c2ee9a12aef32b57d81f5da18ff9a5fc22e/envfiles/kpi.txt#L1), re-run `docker-compose up -d`, and then look in the network tab of your browser's developer console for details about the 500 error. Once you find more information, please share it here and **reopen** this issue (otherwise we might miss it).
