### ISSUE TITLE
New map view disaggregation uses red for many responses

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1660]
When disaggregating by a response that has a lot of options, many appear to be displayed in red, making it hard to distinguish them. Rather, they should use the full gamut of available colors as much as possible. 

![image](https://user-images.githubusercontent.com/673511/37603285-9b28f892-2b64-11e8-8f19-ca4bd071fb5e.png)

**Comment by pmusaraj** [comment]
Yeah, these colors should be generated, regardless of the number of options.

**Comment by mroswell** [comment]
Here is a set of colors for qualitative data, set to the largest number of categories enabled by the app
http://colorbrewer2.org/#type=qualitative&scheme=Paired&n=12

If you wanted to double that to 24, or triple to 36, you could use different shading (Though any more than 12 wouldn't be considered optimal, I can see why more options are potentially needed here.)

Color Brewer is named for Dr. Cynthia Brewer who has spent a career looking at the psychology science of map design.

Keep in mind also, that a percentage of people are color-blind. Far fewer color combinations work in that context. Using different shapes can help in that regard.

For instance, I had red and green in this data visualization, but modified the icon shape so that the content could be distinguished.
http://farmbillprimer.org/charts/roll-call-chart-house-ag-committee-farm-bill-markup/

Here is another set of categorical colors:
http://bl.ocks.org/aaizemberg/78bd3dade9593896a59d

The details there are built into the d3 library, though those colors could be viewed via Dev Tools, or a browser color-selector extension.

This resource requires annoying conversion first to RGB, but could also prove helpful
http://www.zonums.com/online/color_ramp/ 

Also along the lines of shading colors, Andrew Wheeler developed "value by alpha" maps 
such as the first graphic here:
https://andrewpwheeler.wordpress.com/tag/choropleth/
And more on that here:
https://andrewpwheeler.wordpress.com/2012/08/24/making-value-by-alpha-maps-with-arcmap/


Hope something here proves helpful. (I've been doing digital mapping since 1991, so I alert to map-based posts like this one.)

**Comment by pmusaraj** [comment]
This is now ready for testing on `kf.master`. There was a small change to my plan, for a few technical reasons I couldn't use triangular shapes, so I opted instead to use patterns in addition to round/square shapes for the markers.

**Comment by mroswell** [comment]
Nice to know about that MediaLab tool.

I notice that they offer a color differentiation report only for 10 colors or less (and even then, many of the color pairs fail to differentiate). The differentiation issue is just built into what we're trying to do, which is to exceed the standard number of color categories on a map. Probably worth trying your approach.

Don't know if this helps, but sharing in case it ever comes in handy
http://apps.eky.hk/css-triangle-generator/

(One other random thought, is that setting an opacity value can help to surface points on top of points....)

(I'm not actually taking the time to test your proposal, unless asked... still working on other stuff.)
