### ISSUE TITLE
REST services UI elements

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1764]
Designs: https://app.atomic.io/d/PjCNF93XD8wm

I already started work on this in branch `REST-UI`. Please pull that and continue work on this. 

A good amount of the UI work will depend on backend tickets being ready for this (see tickets marked REST, or grouped under the same milestone).

**Comment by magicznyleszek** [comment]
Branch for this: https://github.com/kobotoolbox/kpi/tree/REST-UI

**Comment by magicznyleszek** [comment]
Notes about the design:
* Don't implement the modal for displaying logs, only do the view
* As for security settings crate a select with these options: 
  * "No Authorization" (default?)
  * "Basic Authorization" - displays one (auth token) or two inputs (login and password)
* You could try displaying retry icon-button next to "Failed" status label
* "Learn more" and "Need help?" both should link to a support page that describes REST services: http://help.kobotoolbox.org/managing-your-project-s-data/rest-services

**Comment by magicznyleszek** [comment]
Update on the authorization select:

1. No Authentication
2. Basic Authentication:
  * "Username" input
  * "Password" input
3. Token Authentication
  * "Custom HTTP Header" row(s):
    * "Name" input
    * "Value" input
    * "delete" button
  * "add Header" button that inserts new row

**Comment by magicznyleszek** [comment]
Update: for the list of REST Services add a column with "Failed attempts" that will display a number. Number should be calculated and stored on BE.

**Comment by magicznyleszek** [comment]
Update on auth select:
* use "Authentication" not "Authorization"
* nothing selected on default
* options:
  1. "No Authorization"
  2. "Basic Authorization": displays `username` and `password` inputs
  3. "Advanced Authorization": displays `username` and `password` inputs and Custom HTTP Headers

**Comment by magicznyleszek** [comment]
Endpoint for rest services: `http://[kpi-url]/assets/[asset-uid]/hooks/`

**Comment by magicznyleszek** [comment]
@magicznyleszek note to self: 

REST-UI issues found during testing on kf.master (by @pmusaraj ):
- [ ] I cannot update an endpoint’s URL. it says it saves the change, but when i reopen the modal, i see the old url there. (in fact nothing in that form can be edited.)
- [ ] the “+” button for the custom headers is way too big. Users may confuse this for the “Create” button, so I would recommend either making the button smaller, or collapsing the “Custom HTTP headers” by default.
- [ ] I don’t think we need the Sharing tab, it’s already linked in several places (main list, summary, form landing), so I would propose disabling it here. (It was in the designs, but those designs are now quite dated.)
- [ ] in the individual service view, let’s use “Back to REST Services” instead of “Services list”
- [ ] in the individual service view, the name of the service looks odd on the right.
- [ ] regression: sharing from form list fails, gives white screen with a console error
