### ISSUE TITLE
Allow XLS upload in form list directly via drag-and-drop

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1780]
Bonus point: allow multiple files to be uploaded this way.

**Comment by alnf** [comment]
I hope I understood correctly, that this issue is for data bulk upload (I somehow expected CSV instead of XLS).

I've been using upload via POST requests, and if I'm not mistaken (at last it was some time ago when I tested it) uuid changes each time the entry is edited. So, if someone edited the entry in between my GET and POST it will be added instead of update. Normally, I just ask people not to edit when bulk uploading, but even for one person it is sometimes challenging. For example, last time I was updating around 100 entries (part of it was completely new entries), when I got back 500 ERROR. I figured out it was due to 'à' symbol (which is itself weird, since form creating via XLS went well), but it didn't tell me which row caused it and what part of the data was successfully updated.

What do you plan for the web interface upload? Will it be similar or different as in POST request case?

**Comment by pmusaraj** [comment]
This ticket is for importing forms/projects in bulk. Not data. At this time, there is no plan to import data in bulk via the UI. 

For data, I guess, you have two choices: POST requests to the API is one option, as you mention. The second option, is to use the script in this repo: https://github.com/kobotoolbox/xls-import
