### ISSUE TITLE
Minor issues with SPSS label exports

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2004]
- [ ] SPSS label exports include all languages, but the list of exports shows a particular language:
![image](https://user-images.githubusercontent.com/2085013/46033314-e8b6fa80-c0cb-11e8-9977-821aa4354b28.png)
- [x] The ZIP of labels includes an extra `.sps` file that merely repeats the XML names for each question/choice:
![image](https://user-images.githubusercontent.com/2085013/46033455-3cc1df00-c0cc-11e8-910e-1fc604be55b5.png)

**Comment by jnm** [comment]
:point_right: need to stop sending `lang`, `group_sep`, and `hierarchy_in_labels` to the backend when creating a `spss_labels` export
```json
"data": {
    "lang": "Français",
    "fields_from_all_versions": "true",
    "group_sep": "/",
    "hierarchy_in_labels": "false",
    "processing_time_seconds": 1.544877,
    "source": "https://kf.master.kbtdev.org/assets/an65vn7c6VBvZoQtSGxuX7/",
    "type": "spss_labels"
}
```

**Comment by tinok** [comment]
Nice to have: 

- The SPS label code should therefore add `@` to any variable that starts with `_` (columns generated by KC, ie split geopoint columns and meta fields). SPSS doesn't allow variables to start with `_`. So `_A08_latitude` is turned into `@_A08_latitude` when importing CSV. See [image](https://user-images.githubusercontent.com/673511/47672004-4afd9200-db87-11e8-89d5-8bfe31d54807.png)
- List all labels with a command per row to make debugging easier. SPSS otherwise lists all errors by referring to Line 1 when running VALUE LABELS (or Line 2 for responses). See below example:

![image](https://user-images.githubusercontent.com/673511/47672212-c6f7da00-db87-11e8-9d4c-6ffa0c8d7853.png)
