### ISSUE TITLE
FB preview fails with 'missing column headers' error

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2055]
## Description

I'm not able to preview a simple form on PROD unless the form is first saved. The error is: `The survey sheet is either empty or missing important column headers.`

## Steps to Reproduce

1. Create new form from scratch
2. Add a text and integer question
3. Click on preview

## Expected behavior 

Form previews correctly. 

## Actual behavior 

![image](https://user-images.githubusercontent.com/673511/48071259-e0141280-e1a7-11e8-9158-40cdd752f23e.png)

## Additional details

When saving the form, the preview succeeds.

**Comment by jnm** [comment]
Related to Pyxform upgrade
https://github.com/kobotoolbox/pyxform/blob/f00ec761c989c7f074d757d0b7f03577dda2927d/pyxform/xls2json.py#L325

**Comment by jnm** [comment]
OK, it looks like [we stopped passing `source` to the backend](https://github.com/kobotoolbox/kpi/commit/eb3c22ea32ba9063c425518f87d7da4075fb7075#diff-1e9e28caf1b9bcc1aadb6854611c3b84L308) for unsaved survey previews and started sending `content` instead. I never caught the issue :(

That needs to be reverted. I'm assigning Leszek but may do it myself since it's fairly late in the evening for him.

**Comment by jnm** [comment]
Leszek has fixed the new problem with https://github.com/kobotoolbox/kpi/commit/3bafc75e25fb24a38e015f62619c6f0fbaacda7f, but in the process he identified a much older problem that predates our latest deployment (by long time, I think):
1. Create new form from scratch
1. Add a text and integer question
1. Click on preview
1. Close preview
1. Click on preview
1. `Unknown Enketo preview error` appears
