### ISSUE TITLE
Build new search bubble feature with notification messaging capabilities. 

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/kpi#2183]
## Description

We need to create a MVP for the new help search bubble. The MVP should speed up the initial development and get the feature to deployment quicker. 

Link to [wire frames ](https://app.atomic.io/d/Ct1IMQXckEo3)

## The MVP will:

1. Be launched by expanding the **?** button in the project dashboard
2. Contain outbound links to both the help pages and community forum
3. Allow server admins to send notifications to users and see who has viewed/expanded it and track outbound links
4. Allow users to see a snippet of the notification, which they can either click to expand or close
5. Include a notification badge to remind users the number of notifications they have yet to read.

**Comment by tinok** [comment]
The messaging part should allow 

* [backend] storing multiple messages which can be enabled and disabled based on preset times
* [frontend] displaying multiple notifications at once 
* use user's name (if available) in message, pulling from `/me` endpoint, and substituting with other text if not available
* measure and store interaction stats (# of times displayed, # of times expanded, # of times link clicked (if used)
* user being able to close a message (without reading it), which should show a red circle on it help icon to remind them of the unread message

**Comment by mdestaubin** [comment]
**Notes from Front-End discussion**

- Notifications will have a set time or live/not-live option. It will not be possible for users to see all previously sent notifications, only live messages. 

- There can be multiple notifications at once. When the user clicks on the notification badge/question mark button, snippets will appear in order of newest to oldest for each live notification - all within the same bubble. The user can click on one of the snippets to expand the entire message and then click a back arrow to see the list of snippets again. 

- Notification snippets and links to help center and community forum will exist in the same bubble. 

- It will be easier to develop if the notification messages contain one title, one paragraph, one image, one link, etc., and not multiple of each. 

- Notifications can be sent to all users, as well as specific users based on certain criteria. 

- The "new" feature indication badge will disappear after 5 clicks on the new feature using cookies. 

**Questions**

1. Is it common for users to share credentials for one account? If so, one person may see the new feature badge and it could disappear before another person using the same credentials sees it. 

2. Instead of creating an overlapping notification badge on the question mark button, would it be better to have a separate notification button of its own at the same size as the others and only appear when there are any live notifications? 

**Needed from Back-End**

- List of read or not read notifications, per user

- User intercom status (has access or does not have access)

**Estimated time of work:** 1 week

**Comment by tinok** [comment]
> It will be easier to develop if the notification messages contain one title, one paragraph, one image, one link, etc., and not multiple of each.

I think this is fine, but would be nice to be able to use a link in a paragraph, or include an image between paragraphs. Could allow each field to be optional (other than the title) and allow some limited html or MD in the paragraph field?

> Notifications can be sent to all users, as well as specific users based on certain criteria.

I'd say this sending messages to specific users/based on criteria is beyond the MVP. Initially only need to send to _all_ users. 

> Is it common for users to share credentials for one account? If so, one person may see the new feature badge and it could disappear before another person using the same credentials sees it.

Yes, but I'd assume it's OK if one of the users has seen it. Are you asking whether to store it as a cookie or not? We want to measure whether a user has seen it a message, so after the first user (in browser 1) has seen it, it needs to be marked as 'read'. It could still be displayed to other users in other browsers, but I'd say that's more complicated than we need.

> Instead of creating an overlapping notification badge on the question mark button, would it be better to have a separate notification button of its own at the same size as the others and only appear when there are any live notifications?

Good point. The question is whether the messages are shown in the same 'bubble' as the other links/help resources. In Intercom that is the case. When I close a notification I can read it again, but it will appear in the bubble. My feeling is that keeping them together also promotes the use of the help resources since people will be reminded of their existence whenever there is a notification. But I don't feel strongly about it--- If UX seems better served by having two separate icons/bubbles then let's do it.

**Comment by magicznyleszek** [comment]
> > It will be easier to develop if the notification messages contain one title, one paragraph, one image, one link, etc., and not multiple of each.
> 
> I think this is fine, but would be nice to be able to use a link in a paragraph, or include an image between paragraphs. Could allow each field to be optional (other than the title) and allow some limited html or MD in the paragraph field?

To be specific: it would be easier to manage styling of a known group of data to display (i.e. a title field, a paragraph *with links* field, an image field etc.) instead of managing single message HTML field which can contain anything. So basically we need to decide on a finite possible message contents (because FE needs to be prepared for all possibilities) and then follow this decision both in Admin UI and in KPI.

> > Notifications can be sent to all users, as well as specific users based on certain criteria.
> 
> I'd say this sending messages to specific users/based on criteria is beyond the MVP. Initially only need to send to _all_ users.

Backend would be built differently for "all users only" and "all or selected users" scenarios. If we plan to have this in the future, I think it's better to prepare beforehand. I would guess that having more complex functionality wouldn't add much time costs - but this is a question to @noliveleger or @jnm :smile:

**Comment by jnm** [comment]
@tinok, @mdestaubin, some points of clarification from my meeting with @magicznyleszek are below. Please feel free to edit this message directly with your responses.

* What are some example ways that users would be filtered? This won't be a part of the MVP, but we should have an idea of where we're going so that we can build in the right direction.
    * Also, consider that you've created a filter for users whose names start with J, and it matches 500 users. Would we need to save that list of 500 users and display the message only to them, or do we save only the filter and, upon each request for available messages, check to see if the logged-in user's name starts with J?
* "user's name...substituting with other text if not available": "other text" here would be the username or something else?
* "Allow users to see a snippet of the notification": we will require the message author to specify the snippet (vs. always using the first _n_ characters or words).
* We'll need a way for message authors to preview their message before releasing it into the wild. Proposal: "preview" or "unpublished" mode that restricts message delivery to only its author.
* Messages will have titles, snippets, and bodies. Snippets and bodies will allow Markdown input without restriction; however, some combinations of formatting will likely fail. The message editor/input fields will not be WYSIWYG. It will be the message author's responsibility to preview their messages in the app before publishing them.
    * Maybe useful? https://neutronx.github.io/django-markdownx/
    * Backend will convert MD to HTML during serialization when serving to the frontend
* :warning: **Unresolved:** where will images be stored? I'm guessing we'll have to store them through Django using something like [`ConfigurationFile`](https://github.com/kobotoolbox/kpi/blob/94d88be1640f833b1d530180fe693b399b5cc427/hub/models.py#L18), but easier alternatives might include Base64 URLs (probably too ugly from the editor's standpoint) or external hosting.
* Messages will be composed in the Django admin interface
* This strikes me as beyond MVP: "measure and store interaction stats (# of times displayed, # of times expanded, # of times link clicked (if used)." We can do it for the first release if necessary, though. Does this assume **one link only**, or are we tracking clicks for an arbitrary number of links per message?

### Musing on the JSON interchange for this (not finalized)
`GET`ting messages—the server responds:
```json
{
  "mMessageUID1234": {
    "title": "Very Important Announcement Title",
    "snippet": "You had better click this!",
    "body": "Haha, fooled you!",
    "readTime": null,
    "validFrom": "2070-12-01T01:23:45",
    "linkClickedTime": null,
     ...
  },
  ...
}
```

The client could `PATCH`:
```json
{"nBlah123": {"readTime": "2077-12-01T01:23:45", ...}}
```

**Comment by tinok** [comment]
> What are some example ways that users would be filtered? 

* Only users who have been online within the last 30 days
* Only users with more than (or less than) 2 deployed projects

> Also, consider that you've created a filter for users whose names start with J, and it matches 500 users. Would we need to save that list of 500 users and display the message only to them, or do we save only the filter and, upon each request for available messages, check to see if the logged-in user's name starts with J?

* I guess the second one seems better since it can apply to newly created users as well. 

> "user's name...substituting with other text if not available": "other text" here would be the username or something else?

* `Hi {first_name}|{"there"}` is what I have in mind, based on what Intercom does. If field is empty, fall back on hardcoded text, to be supplied in the notification. If not specified, just don't insert anything.

> This strikes me as beyond MVP: "measure and store interaction stats (# of times displayed, # of times expanded, # of times link clicked (if used)." We can do it for the first release if necessary, though. Does this assume one link only, or are we tracking clicks for an arbitrary number of links per message?

* Not needed in MVP. Assumes any number of links, we should be tracking clicks for any of them. 

> We'll need a way for message authors to preview their message before releasing it into the wild. Proposal: "preview" or "unpublished" mode that restricts message delivery to only its author.

* Great idea!

**Comment by jnm** [comment]
### Backend requirements

- [ ] New message model
- [ ] Messages have a plain-text `title`
- [ ] Messages have Markdown `snippet` and `body` fields
- [ ] Messages can be created and edited in the Django admin interface
- [ ] Markdown fields use Github-flavored Markdown
- [ ] Markdown fields show a live preview while editing
- [ ] Images can be uploaded by dragging-and-dropping onto the editor
- [ ] Images have persistent URLs
- [ ] Images are stored locally or in S3 depending on the Django media file configuration
- [ ] Messages have `datetime` fields dictating the beginnings and ends of their validity
- [ ] Messages record the identity of their last editor
- [ ] Messages can be `published` or not, where `published=False` means only the last editor sees the message within the application (all messages are visible in the Django admin interface)
- [ ] API exposes messages only to authenticated users
- [ ] API exposes only valid messages (based on server time and message `datetime` fields)
- [ ] API honors `published` setting
- [ ] API returns HTML for Markdown fields
- [ ] Markdown-to-HTML conversion treats the input as a Django template
- [ ] Template context includes `request.user.extra_detail` as `user` (for `name`, etc.)
- [ ] API sorts messages descending by primary key, i.e. the most recently created message is at the top of the list. Modifying a message does not affect sorting. Creation and modification times are not actually recorded.
- [ ] Superusers can create and edit messages via the API (in addition to the Django admin interface)
- [ ] Some way to record that a user has read or dismissed a message. Does that mean just building the non-MVP stuff in the MVP‽
- [ ] **(non-MVP)** API has endpoint for recording whenever a message (`title` and `snippet`) is displayed to a user
- [ ] **(non-MVP)** API has endpoint for recording whenever a message is dismissed by a user without having been opened
- [ ] **(non-MVP)** API has endpoint for recording whenever a message is opened (`body` shown) by a user
- [ ] **(non-MVP)** API has endpoint for recording whenever a link inside a message is clicked by a user
- [ ] **(non-MVP)** Message authors can limit which users see a message by specifying filter criteria (finish [this work](https://github.com/kobotoolbox/kpi/compare/phil-magic-query-parser), but it might not suffice for counts and joins). The filter criteria themselves are stored, not the results.
- [ ] All this is tested! What's the best way to test the Django admin interface?

**Comment by magicznyleszek** [comment]
To summarise latest discussion with @mdestaubin and @tinok at https://www.flowdock.com/app/kobotoolbox/kobo/threads/r5U1k4B80WDqGPCf2RTaCzg0wRv :

1. messages should have two flags: `acknowledged` and `read`
  - `acknowledged` makes the message display immediate and always for users, until they dismiss (clicking "x" button) or open it
  - `read` makes the message display the red badge and appear as read/unread on the list of messages, until user opens it in full view
2. drop username and avatar, display `title` instead
3. icon button has different click actions:
  - if there is _one_ un`acknowledged` message, clicking it opens the message in full view
  - if there are _zero_ or _multiple_ un`acknowledged` mesages, clicking it opens the default view with list of all messages
  - opening the default view does __not__ make the messages `acknowledged`
4. try to keep the bubble the same height for message in full view and default view
