### ISSUE TITLE
`note`s must be marked as read-only

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2198]
Reported by users: https://community.kobotoolbox.org/t/my-note-questions-are-suddenly-appearing-with-a-text-field/2332

We're now generating XML for `note`s like `<bind nodeset="/data/what_s_up_sir" readonly="false()" required="false()" type="string"/>`, which appears in Enketo as
![a text input.](https://user-images.githubusercontent.com/2085013/52977463-56293780-339b-11e9-8b30-9ed49c822c73.png)

[According](https://www.flowdock.com/app/kobotoolbox/enketo/threads/gvtVRBZN8KxO5-_wcct8sElwv7Z) to Martijn:
> From an XForm perspective a note doesn't really exist. This is just a text input with `readonly="true()"` (and no value and no calculation)

We added support for toggling `read_only` in the form builder with https://github.com/kobotoolbox/kpi/pull/2147, but a side-effect of this evidently is making all fields non-read-only by default. **We need either to stop explicitly setting `read_only` when the user hasn't modified it, or to add some kind of exemption list for question types that should never have `read_only` set to `false`.**

**Comment by jnm** [comment]
@magicznyleszek, I'll take a stab at this, but if you have an idea of the best way to go, let me know.

**Comment by tiritea** [comment]
Note, by default, read-only is false in XForms. So its somewhat preferable not to even specify it in the XML unless its being set to true() or an XPath expression, otherwise - if its present - the XForm client is rather obligated to evaluate whatever the XPath expression is (which is a waste of time if its 'false()'...)

>add some kind of exemption list for question types that should never have read_only set to false

I dont think this is workable, since in practice its possible to set a default value for pretty much any question type value, and then set the associated binding to read-only='true()' in order to make the default non-editable. Rather, I think you might instead maintain a list of all XLSForm question types were read-only must always be set to true; namely notes (and disable/remove the read-only checkbox in settings for notes).

**Comment by jnm** [comment]
@tiritea, thanks. We'll reference this conversation when we find a non-breaking way to re-implement #1726.
