### ISSUE TITLE
Permissions to access form still active after form/project deletion

### ISSUE THREAD

**Issue by Qwent** [kobotoolbox/kpi#2206]
## Description

When a permission to submit is granted to another user, and the form is then deleted, the form is still visible from KoBoCollect when connected with the other user (even though it is impossible to download the form as it has been deleted).

It seems that the form and its data are correctly deleted, but not the permissions associated with the form.

## Steps to Reproduce

1. Create new form with user A and allow user B to submit data to the form (settings -> permission)
2. Delete the form and its data with user A account.
3. Connect with user B to KoBoCollect and try downloading the blank form 

## Expected behavior 

The form should not be visible to the user B as it has been deleted by user A.

## Actual behavior 

The form is still visible for user B in blank forms. However when user B tries to download it, an error is returned (the form is not available). It seems that there is no way to delete it, and user B will be stuck with this undownloadable form in its blank form menu forever.

## Additional details 

Removing permissions to user B before deleting the form solves the bug.

**Comment by jnm** [comment]
Hi @Qwent, thanks for the report. I'm having trouble reproducing this. Have you clicked the Refresh button in KoBoCollect after deleting the form? If so, please try logging in to a web browser as user B and then visiting https://kc.kobotoolbox.org/formList (replace `kc.kobotoolbox.org` with your KoBoCAT server, e.g. `kc.humanitarianresponse.info` for OCHA). If the deleted form is not present there, then the problem lies in the Android device or Collect application. Thanks!

**Comment by Qwent** [comment]
Hi @jnm ! Neither am I able to reproduce the trouble ! It's weird... I'm sorry, as you mentioned it should be because I did not refresh the form list (even though I tried several times before posting the issue).

Sorry for the inconvenience.

**Comment by jnm** [comment]
OK! Thanks for the update. Let us know if the problem comes back: you can reopen this same issue #2206 on GitHub if it does.
