### ISSUE TITLE
EDIT button opens wrong submission

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2217]
1. Create a form with at least one question whose responses will make submissions easy to distinguish;
1. Deploy;
1. Collect 2 or more submissions;
1. Open the table view;
1. View the first submission;
1. Click NEXT to view the second submission;
1. Click PREVIOUS to view first submission again;
1. Click EDIT;
1. Observe that the submission shown in Enketo is second(!) submission.

**Comment by magicznyleszek** [comment]
@jnm I was looking into it, and discovered that on step 7 when FE calls for enketo edit link for submission, BE sends `{"detail":"Not allowed. Record is already being edited"}` instead of `{"url":"http://ee.kobo.local/edit/::xO9eFOGx?instance_id=e24619c5-6485-478b-8c79-35d5e4c8df26&returnUrl=false"}`. And mind you that I didn't do anything with submissions, just followed the repro steps

**Comment by magicznyleszek** [comment]
One more thing: this has two bugs really: first one above (wrong BE response?) and second one is the AJAX delay for setting edit url (as FE calls for edit url after submission call data is set, thus making the edit url from old submission until the second call get's there). I am fixing the second one plus I will display helpful error message that I got from BE.
