### ISSUE TITLE
Display images rotated according to their EXIF orientation

### ISSUE THREAD

**Issue by djordjemarusic** [kobotoolbox/kpi#2241]
## Description

EXIF information of the photos are not taken into account.

## Expected behavior 
A submitted photo should be presented according to the orientation described by EXIF.

## Actual behavior 
If a user submits a photo with EXIF rotation information, a photo will not be presented in proper orientation.

**Comment by jnm** [comment]
Is there a good library for this? It looks like something we probably wouldn't undertake from scratch: https://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/

**Comment by duvld** [comment]
Hi there, I've tried to reproduce this with the examples that the author of the article that @jnm linked above (https://github.com/recurser/exif-orientation-examples). I'm not sure exactly what is expected here.

When I upload these images, which is two sets of images with every EXIF orientation, it looks like they are displayed in the submissions with the original orientation. I.e., if the original orientation is upside down and mirrored, the submission shows it as upside down and mirrored. Do we want to change this or is this the expected behaviour? I've confirmed it works on Firefox, Chrome, and Opera.

**Comment by djordjemarusic** [comment]
Yes, that's true and I would like this to change. If the EXIF information is taken into account, all the images in the set would be displayed identically - as the first image in the set. That is, they would be rotated or mirrored if needed.

**Comment by jnm** [comment]
Maybe this will do it?
https://stackoverflow.com/a/27882870/2402324
```css
img {
    image-orientation: from-image;
}
```

**Comment by magicznyleszek** [comment]
@jnm I've merged the solution that works in Firefox and in ~~upcoming~~ Chrome 81 and in any other modern browser that will start using `image-orientation`.
