### ISSUE TITLE
Repeat group data not exported in non-legacy xls or csv output.

### ISSUE THREAD

**Issue by Santosh07** [kobotoolbox/kpi#2337]
## Description

Data for repeat groups are not exported in non-legacy output mode.

## Steps to Reproduce

1. Create a form with question that repeats according to a number that is input by user.
2. Input data and upload/save.
3. Export this data in non-legacy csv or xml format.

## Expected behavior 

All data related to 'repeat' question is available in exported file.

## Actual behavior 

Data for 'repeat' question is not available in exported file.

**Comment by jnm** [comment]
Hello, it's a known limitation that CSV exports don't contain repeating groups. Excel (XLSX) exports do contain repeating groups: the responses for each repeating group are placed on a separate worksheet. You mentioned "xml format," but I'm assuming that's a typo (correct me if otherwise).

If Excel exports don't work with repeating groups for you, please post the details of your form in https://community.kobotoolbox.org/c/kobo-users.

If you would like to see CSV exports include repeating groups in some way—this would need a new approach since CSVs cannot contain separate worksheets—please post your idea of how it should work in https://community.kobotoolbox.org/c/feature-wishlist.

Thanks for your report.
