### ISSUE TITLE
Button for displaying submission using Enketo read-only view

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2607]
## Description

A button "Preview in Enketo" could be added in Submission View and possibly in the Table View. 

The idea behind this is to allow previewing submission in Enketo, because it will always look same as when filling the form, so if our submission view is not good enough, user could use this option and "Edit in Enketo" could work for this, but it is available only if you have edit permissions.

There is an endpoint that gives Frontend edit link: `GET /api/v2/assets/{uid}/data/{id}/edit/?return_url=false` so we could make a similar one for getting preview link, e.g. `GET /api/v2/assets/{uid}/data/{id}/view/?return_url=false` - it would use Enketo's https://apidocs.enketo.org/v2#/post-instance-view

## Additional details

There is already an issue for kobocat: https://github.com/kobotoolbox/kobocat/issues/460 with PR https://github.com/kobotoolbox/kobocat/pull/513 that noone is reviewing at this moment.

**Comment by tinok** [comment]
The user story for this is:

_As a survey administrator I want to view a single survey submission in the Enketo format (but without having to worry about accidentally editing it) in order to view the form exactly how the enumerator saw it._

@magicznyleszek Do you have a suggestion on where / how the button would be displayed? I agree it would make sense to have access to it in both the table and single submission view, but need a good UI design to make sure we don't add confusion with another button.

@Ig-Rebollo can you work on a design for both views (table and single submission)? 

One UX question is whether this should **REPLACE** the current single submission view since it very much serves the same purpose.

**Comment by Ig-Rebollo** [comment]
That makes a lot of sense, I actually thought of a similar thing when going
through the app and platform last week. I'll start working on it.

*Ignacio G. Rebollo*
Strategic Design & Visual Communication.
igrebollo.com   I   Behance <https://www.behance.net/igrebollo>   I
 @IGRebollo

**Comment by jnm** [comment]
The KoBoCAT PR will not be merged given our intention to remove all UI from KoBoCAT.

I think there's still value in the current submission modal, as it's a much more concise view of responses than showing the entire form in Enketo. Of course, my perspective could be totally at odds with real users' :smile:

> I want to view a single survey submission in the Enketo format…in order to view the form exactly how the enumerator saw it.

:point_up: Understanding that many (most?) submissions come through the Collect application, the Enketo view has very little to do with what the enumerator saw.

:warning: We can only load _one version_ of the form at a time in Enketo. Right now, that's always the currently deployed version of the form. If a submission was collected with an earlier version, and that version had questions that were changed or removed, responses aren't going to appear correctly. A separate task to improve this would be to look up the version for each submission and load that into Enketo. If the submission references a version that we don't have in our database for some reason, well… :grimacing: I believe the current submission modal (and table view) fall back to showing the XML name of the question and the response.

**Comment by magicznyleszek** [comment]
Plus on the current submission view, we have `start`, `end`, `__version__` and `instanceID` displayed that (I may be wrong) is not available when previewing in Enketo.

My initial idea would be to have this available on table view (eye icon merged with enketo logo?) between "view" and "edit", plus in the submission view a button next to "EDIT".

**Comment by tinok** [comment]
Agree, there is value in both views. The question is whether one of them could become the default, or whether you need to click on the existing submission view to get to the Enketo view. 

@Ig-Rebollo will come up with a suggestion on how to access the additional preview. The current one is not obvious for existing users so there is scope to improve it rather than adding just another icon that people don't intuitively understand.

**Comment by Ig-Rebollo** [comment]
I have been thinking about this issue for a while and getting more familiar with how it's currently done. After weighing different options, I feel quite strongly that adding a third button will only add noise and make things more confusing for most users. It would serve the same purpose the current submission modal does, just with a different design. 

In my opinion what the user story proves is:

A- That this user prefers to use the enketo format, but would rather have the fields locked so he/she doesn't have to worry about editing something by mistake. 
B- There is a desire for consistency throughout the process: They want to see it as the enumerator saw it.
C- The design of the current modal breaks that consistency, as it is not seen or used in any other instance throughout the process. Enketo users see a different format, but also those who use KoBo Collect don't see that table design until they check the website.

Bearing this in mind, my suggestion would be to maintain the icons as they are, but change the current submission modal to look either exactly like, or very similar, to the Enketo form. Ideally, the change from view to edit would be completely seamless. You could view the form submission with the same design than Enketo, and in it, click a button that says 'edit', which would unlock the fields for you to edit. While editing the button would change to say 'save', so you can click in the same place to save and exit the edit format. I can make a mockup of this if it is not clear in text.

Not sure if this would be a viable solution @tinok @magicznyleszek @jnm, but it is likely the best way to go from a usability standpoint. If we want to be sure about it before implementing anything, we could create PDF mockups with the option I just described and another one with the initial idea of having three buttons, and test them with some users to see which one scored better. Sort of a rudimentary A/B testing (of course if you guys can implement real A/B testing on the site, that would be even better!). Let me know what you think.

**Comment by tinok** [comment]
@Ig-Rebollo This is a great suggestion from a usability point. It is already possible to see the single submission data in Enketo format **without** being able to edit it. For now this is not available to users though technically possible. That's what this issue is trying to add to the UI. 

This would imply that the user can either click on the view or edit buttons, which both exist already. The view button would bring up the Enketo read-only view while the edit button brings up the Enketo edit view. In the read-only view there could be a button to **Edit submission**. 

Is that what you suggested? 

Doing away with the current single submission view has two issues: 1) users are used to it and may have built workflows around it; and 2) it is much more compact than the Enketo view for printing and viewing.

**Comment by joshuaberetta** [comment]
Closed by https://github.com/kobotoolbox/kpi/pull/2993
