### ISSUE TITLE
Finish conversion of JSON fields stored as text to jsonb

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2635]
OK to proceed now! :+1: ~~We need to do a release after #2632 is merged.~~ Then, for a subsequent release, we can:
- [ ] Assume everyone has either run `0024_alter_jsonfield_to_jsonbfield` or `migrate_json_text_to_jsonb`, and therefore use `django.contrib.postgres.fields.JSONField` (import `as JSONBField`) everywhere (revert https://github.com/kobotoolbox/kpi/pull/2632/commits/cc6a31dd6801601d5dfde567c2a226beea4a934d, making sure to remove `_filter_by_source_kludge()`);
- [x] (done in https://github.com/kobotoolbox/kpi/commit/2bb75106c3aaf27b4eb89ffaa875982369c1267f) Consider that all columns migrated by `migrate_json_text_to_jsonb` will now be `not null`: https://github.com/kobotoolbox/kpi/blob/72c0161e7deae30cc948841a7b1d2bb65a9e3cc6/kpi/management/commands/migrate_json_text_to_jsonb.py#L12-L22
    Change the Python code to reflect the `not null` constraint;
        * Model definitions;
        * ~~New migrations~~ `0024_alter_jsonfield_to_jsonbfield.py`.

**Comment by noliveleger** [comment]
@jnm In https://github.com/kobotoolbox/kpi/pull/2661. Please note I have deactivated the unicode test because it failed with `JSONBField`.
https://github.com/kobotoolbox/kpi/pull/2661/files#diff-8f7b0d0050953717eb6f924c0618ff3cR165-R168

I have also restored the `None` value on `AssetSnapshot` objects creation.
https://github.com/kobotoolbox/kpi/pull/2661/commits/13958aa868853d4dd7c185e0ac25d4a1fc0711a5#diff-43986855ae1015d5975b107cf1ee9869R1095-R1104
