### ISSUE TITLE
Granted users cannot see nested menu of `Settings`

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2647]
## Description

Users with `Edit Form` (and implied permission `View Form`) cannot access to:

- `Settings > Media`
- `Settings > Sharing`
- `Settings > Rest Services`

## Steps to Reproduce

1. Grant permission `View Form` and `Edit Form` (only) to  `UserB`
2. Log into `UserB`'s account
3. Try to access one of the menus above. 

## Expected behavior 

Access to each panel

## Actual behavior 

> Access Denied
> You do not have permission to view this page.

## Additional details

`UserB` is able to open sharing modal from 3 dots from `Form` panel (i.e. no Access Denied)
If `View Submission` is added. It works as expected.

Related to discussion in #2646

**Comment by jnm** [comment]
I think if I have "Edit Form" I should be able to see "Settings -> Media", because this media is part of the form definition only, not attachments that were included with submissions.

I think if I have "Edit Form" I should also see "Settings -> Sharing", because I can already "open sharing modal from 3 dots from Form pane."

I think if I have "Edit Form" but not "View Submissions", I should **not** be able to ~~access~~ change anything in "Settings -> REST Services", because configuring my own REST Service would give me a backdoor to seeing submitted data.

**Comment by jnm** [comment]
Whoops, this isn't going to work while "Settings -> Media" is still a KC iframe:

> I think if I have "Edit Form" I should be able to see "Settings -> Media", because this media is part of the form definition only, not attachments that were included with submissions.

We can deal with it properly when we remove the KC iframe in favor of https://github.com/kobotoolbox/kpi/issues/2487.

Until then, we should restrict "Settings -> Media" to form owners only, since as far as I can tell no one else will ever be able to edit KC media: `change_asset` in KPI grants nothing in KC per https://github.com/kobotoolbox/kpi/blob/81f5ba420bc366d13cd1fbed66769d4fe487dc7f/kpi/models/asset.py#L599-L604
