### ISSUE TITLE
Add new permission for permissions editing

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2648]
Relevant older issues: #1527, #1528 

`Edit Form` can lead to confusion about permissions editing.
Granted users with this permissions are allowed to change project's permissions for other users and themselves.

We could add a new permission for permissions editing and restrict users to change permissions if they have `Edit Form` only.  

@magicznyleszek, @Ig-Rebollo In the meantime, we could do add a message telling people what `Edit Form` implies when it's checked?

Related to discussion in #2646

**Comment by magicznyleszek** [comment]
@noliveleger should we use a `name` field from `api/v2/permissions` for this permission? We would need to change the content of this field for `change_asset`, as currently it says "Can change asset". I'm asking because I remember this field used to be named "description" and it seems to contain descriptions of permissions and Frontend doesn't use them anywhere.

**Comment by Ig-Rebollo** [comment]
@noliveleger @magicznyleszek is this what you are referring to? Wondering if adjusting the wording of the option would be enough. Otherwise I think the space between the options checkmarks and the 'grant permissions' button would be the perfect spot for a note, warning, or even general description of all the options selected.

![image](https://user-images.githubusercontent.com/22472326/81319735-13b25000-905e-11ea-8cc7-417e60e9db9f.png)

**Comment by magicznyleszek** [comment]
@Ig-Rebollo yes, this is the modal we are talking about :) Maybe a "(?)" icon that shows a tooltip with description next to permission? Note that we use the same names in an inline list for displaying existing permissions:
<img width="594" alt="Screenshot 2020-05-07 at 18 34 09" src="https://user-images.githubusercontent.com/2521888/81320415-6fe29780-9091-11ea-827c-abca71d6c239.png">

**Comment by Ig-Rebollo** [comment]
The problem with tooltips is that most people tend to not hover/click on them unless the term they accompany is difficult to understand otherwise. 'Edit form' is already pretty self-explanatory and I feel most will simply make their own assumptions and move on without using the tooltip.  

If the use case here is more to warn people of the implications of selecting this option, it should be visible automatically when checked in the sharing permission modal. For the inline list of existing permissions though, it might be a good option to use the tooltip, or an (*) with a note below...

**Comment by noliveleger** [comment]
> @noliveleger should we use a `name` field from `api/v2/permissions` for this permission? We would need to change the content of this field for `change_asset`, as currently it says "Can change asset". I'm asking because I remember this field used to be named "description" and it seems to contain descriptions of permissions and Frontend doesn't use them anywhere.

@magicznyleszek, it will be changed if we insert a new permission. 
Indeed, it's the description. The label has been changed a reason related to Django I think but I don't remember exactly what. Maybe @jnm does. 
We had this discussion quite a few times (about FE should read the ~~description~~ name from BE) but I think, it was needed to hardcode it in FE for some reason (which I don't remember either :-( ) .
