### ISSUE TITLE
Basic UI for form media uploads (matching KC functionality)

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2673]
Split from https://github.com/kobotoolbox/kpi/issues/2487, which has a more thorough redesign of form media.

Building on https://github.com/kobotoolbox/kpi/pull/2537, please add a basic form-level UI for uploading media files. It should do everything that KC's "Form Files" interface does, which we currently show in KPI using an iframe:
![image](https://user-images.githubusercontent.com/2085013/81957734-04da1900-95db-11ea-985a-f7367a166662.png)

* Upload single files
* Upload multiple files (I only noticed this was possible a few days ago _!_ )
* Add media URLs (pending back-end support)
* View current files
* View current URLs
* Delete files
* Remove URLs

The `change_asset` permission is required to do this stuff.

~~I think this removes our last UI dependency on KoBoCAT! :tada:~~
(oh no, the gallery :cry:)

**Comment by tinok** [comment]
Can we implement this 'basic UI' similar to this wireframe? Just instead of a modal put it within the confines of the Media settings page?

![image](https://user-images.githubusercontent.com/673511/81968623-a321ab00-95ea-11ea-8bf7-1ff19069edf5.png)

**Comment by tinok** [comment]
> I think this removes our last UI dependency on KoBoCAT! 🎉

@jnm I'm sorry to point this out, but our image gallery still uses KC through an iframe..

**Comment by Ig-Rebollo** [comment]
@jnm @tinok I think that makes a lot of sense, not just for the practicality of reusing design but also for the sake of navigation consistency, which will increase the overall usability of the site.

This is my first attempt at repurposing the -latest version of the- modal to upload media for this page. Let me know what you think.

![image](https://user-images.githubusercontent.com/22472326/82614846-cc1be000-9b96-11ea-990c-51d8c7b67a12.png)

[Here a higher definition PDF](https://drive.google.com/open?id=1ri_oty0_b4xLI8uTj9bOYpzoi0OjbMQM)

**Comment by magicznyleszek** [comment]
FYI, we already have a component that is being reused in multiple places like that - Project Settings are used in 1) New project modal, 2) Form Settings General route, 3) Form Builder's Layout & Settings pane.

**Comment by duvld** [comment]
@Ig-Rebollo should we be trying to keep the same look as the formbuilder modal? It would make it easier to be able to render the same form instead of making a new one for the `settings/media` page. I've made the skeleton in @tinok 's picture above in `settings/media`:
![image](https://user-images.githubusercontent.com/16762675/82694425-384b2200-9c31-11ea-930f-1c8e0aef1531.png)
(I don't know why the screenshot has a box in the top left, it shouldn't be there)

**Comment by Ig-Rebollo** [comment]
@duvld yes, that definitely works, no need to put drag/drop and URL side by side really. In terms of files uploaded to this project though, there might be some changes (i.e. displaying the thumbnails) for the form builder modal as well, but in any case yes, the goal in the end is that both the form builder modal and the settings/media page use the same design/look.

**Comment by duvld** [comment]
@Ig-Rebollo thanks for the feedback :) I wanted to make sure that we were trying to have the same modal for each instance of the form. I'm currently trying to get this skeleton functional, after which we can fine tune the look and feel.

**Comment by noliveleger** [comment]
@duvld, everything works as expected. 
I see some CSS issues. I know it's a temporary step, so I apologize in advance whether there are known:

- Height of the button `Add` is bigger than the textbox. 
- The textbox right edge and the button left edge corners have rounded corners. Maybe we should make the corners straight to see both elements as the same component?  Or add some space between both elements?
![Screen Shot 2020-06-03 at 09 28 59](https://user-images.githubusercontent.com/24226825/83642547-fac58d80-a57c-11ea-8c4e-1891bd2460de.png)
- Nothing is displayed to users when uploading a file. I've made a test with a slow connection (Chrome dev tools with slow 3G connection) with a 3 MB file, it can take several seconds before the file appears in the list. I would use the same behaviour as exports. Add the row as soon the upload begins and update the row every X seconds until the upload is done.

What do you think?

**Comment by Ig-Rebollo** [comment]
Hi @duvld thanks for sharing the staging site. Some comments/suggestions based on what's up there so far (ignore if you're still working on it!)

![image](https://user-images.githubusercontent.com/22472326/83817150-06ef3f00-a692-11ea-8f5b-2705ccfae4e7.png)
1. The dashed border might be too thin and dark. I would make it 5px width, 16px border-radius, and a lighter gray, such as #E6E6E8 
2. The icon might also be too big. I would reduce it at least to around 50x50px (vs the current 72x72) or even smaller.
3. Drag and drop and URL text should be the same size. I would make the 'click here to browse' smaller though, that's why I originally broke it in two lines.
4. Agree with @noliveleger , there should be either a separation or remove the round corners on that side of the button and text box. However I think an even more consistent and easy solution might be a style like the one you have in Settings/General (i.e. a simple line that becomes blue when clicking on the area)
5. This section should have at least the hint of a table (for example top and bottom lines) with a message saying there are no files uploaded yet.

I tried to compile all of this in a quick mockup for reference. I can give you more specs on particular elements if needed. Let me know!
![image](https://user-images.githubusercontent.com/22472326/83817738-8af5f680-a693-11ea-81f1-077721309135.png)

**Comment by tinok** [comment]
@Ig-Rebollo I think we should include a link somewhere to explain this feature. We use a blue ? button in other places and sometimes a text hint (Click here to learn more..).

**Comment by tinok** [comment]
This is a ? button in the cascading select modal: 

![image](https://user-images.githubusercontent.com/673511/84398108-85d20380-abcd-11ea-8a2a-b8c850bf70d6.png)

Here's one you used in #2487: 
![image](https://user-images.githubusercontent.com/673511/84395950-30e1bd80-abcc-11ea-9984-f3b363be87f1.png)

In other places we use a text hint:
![image](https://user-images.githubusercontent.com/673511/84398041-6e931600-abcd-11ea-9956-4fd66f00ca71.png)

would be nice to settle on a single format and start using it more widely in other advanced features.

**Comment by Ig-Rebollo** [comment]
Here a quick mockup of how it would look on this screen:

Idle mode:
![image](https://user-images.githubusercontent.com/22472326/86402052-338a7c80-bc79-11ea-8e50-c20621c460c4.png)

On hover (active)
![image](https://user-images.githubusercontent.com/22472326/86402092-4309c580-bc79-11ea-8dbc-86d0d1892fd0.png)

If we settle on this way (or any other really), it should look and behave the same way everywhere else.

**Comment by tinok** [comment]
The settings section on the left says "Media" yet on the right we just use "files" everywhere. I think we should use "media files" instead. 

"You can also... " should use the singular ("You can also add a media file using a URL").

Maybe the tooltip could be "Learn more about this feature..."?

I find "File(s)" quite ugly. Could we just use "Media files" or "Uploaded media files"?

**Comment by Ig-Rebollo** [comment]
@tinok @magicznyleszek adding here some updated mockups incorporating the language changes Tino mentioned, and adopting the latest version of the UI with the simplified colors/backgrounds (disregard any differences you find between these mockups and the latest merge outside of the 'attachments' section itself)

![Attach-files](https://user-images.githubusercontent.com/22472326/93649712-9ff45c80-f9da-11ea-8de4-14ecd84c3082.jpg)
![Attach-files-info](https://user-images.githubusercontent.com/22472326/93649729-a551a700-f9da-11ea-834e-d9a9e7ad3f37.jpg)
![Files-attached](https://user-images.githubusercontent.com/22472326/93649736-a84c9780-f9da-11ea-83f7-b1dce5ac68f6.jpg)

**Comment by tinok** [comment]
Note: Mostly complete in https://github.com/kobotoolbox/kpi/pull/2695, still waiting on  https://github.com/kobotoolbox/kpi/issues/2674 before this can be merged and this issue can be closed.
