### ISSUE TITLE
Blank group titles resulting in unwanted titles with blank spaces

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2676]
## Description

When you have a survey form with the `grid them layout` and `groups with titles` the `preview` gets messed up as shown in the image below:

![image](https://user-images.githubusercontent.com/50188479/82081731-8e3a3a00-9706-11ea-9632-e5f956699c66.png)

But if you fix the same `grid them layout` xlsform by providing `groups without titles` the `preview` seems OK as shown in the image below:

![image](https://user-images.githubusercontent.com/50188479/82081998-f426c180-9706-11ea-901f-4a4cd9ba0ada.png)

## Steps to Reproduce

1. Upload Group & Label (Image 1) xlsform and preview you will see the messed up preview.
2. Upload Group & Label (Image 2) xlsform and preview you will see a clean preview.

## Expected behavior 

Groups shouldn't be messed up while previewing (as shown in the image above).

## Actual behavior 

Groups are messing up while previewing (as shown in the image above).

## Additional details

**Reference xlsform: That shows distorted preview**
[Group & Label (Image 1).xlsx](https://github.com/kobotoolbox/kpi/files/4636276/Group.Label.Image.1.xlsx)

**Reference xlsform: Where the preview is OK**
[Group & Label (Image 2).xlsx](https://github.com/kobotoolbox/kpi/files/4636286/Group.Label.Image.2.xlsx)

**Flowdock:** 
https://www.flowdock.com/app/kobotoolbox/support/threads/w7pzaSyCBbROAcUz7riyBWkhExs

**Comment by duvld** [comment]
A possible fix for this issue would be to ignore all group labels when a form is a `grid-theme` type. A non-hacky way of doing this may require BE work. The issue of #2707 seems to be coming from the translations so I created a separate issue for that.

**Comment by jnm** [comment]
Hi @Kalyan-Lama, I don't think this is a bug as described. I understand that this is not desired for a matrix:
![image](https://user-images.githubusercontent.com/2085013/100835307-6bba0500-343b-11eb-9478-d338d87641a9.png)

However, that's what is going to happen when the form specifies labels for the groups inside the matrix, as `Group & Label (Image 1).xlsx` does:
![image](https://user-images.githubusercontent.com/2085013/100835421-9c01a380-343b-11eb-8e46-74094d7b1683.png)

The `Group & Label (Image 2).xlsx` form does the right thing by leaving the labels blank for these internal matrix groups. There used to be a warning against leaving group labels empty, but we removed it (#2526) for situations just like this.

The title of this issue is "Blank group titles resulting in unwanted titles with blank spaces," and although the description doesn't describe that situation, I believe @duvld has tracked it at #2707.
