### ISSUE TITLE
Error message seen while trying to filter a record by _uuid under DATA>Table (OCHA, HHI and self hosted servers)

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2770]
## Description

Error message seen while trying to filter a record by `_uuid` under `DATA>Table`. This issue prevails in all the servers viz. OCHA, HHI as well as self hosted servers.

## Steps to Reproduce

1. Go to `DATA>Table`.
2. Copy a `_uuid` code that you wish to filter (the record associated with) and then paste it under the blank space seen under `_uuid` as shown in the image below:
![Image 101](https://user-images.githubusercontent.com/50188479/91197337-eb3c8780-e71a-11ea-9cbe-9c732cb593aa.png)
3. Press enter. You should see the following error message:
![Image 102](https://user-images.githubusercontent.com/50188479/91197357-f42d5900-e71a-11ea-9ec7-ce73d3c80dd0.png)

## Expected behavior 

Users should be able to filter records like it's possible with other fields.

## Actual behavior 

Error message seen while trying to filter a record by `_uuid` under `DATA>Table`.

## Additional details

**Link to the community forum:** https://community.kobotoolbox.org/t/bug-data-table-view/11837

**Comment by duvld** [comment]
On my local production I get a more helpful response:

![image](https://user-images.githubusercontent.com/16762675/91204839-a1c84a00-e6d2-11ea-910d-04ecbdd0a363.png)

Turns out it is a python error stacktrace that is showing up locally for me because of the debug setting(?)

Here's the first entry in the stacktrace:

![image](https://user-images.githubusercontent.com/16762675/91205275-4b0f4000-e6d3-11ea-9e9b-14cbac64fdfe.png)

Here's the [stacktrace](https://github.com/kobotoolbox/kpi/files/5125313/2770-stacktrace.pdf) in its entirety, for some reason devtools don't show the response as a html page, so I had to make it myself

Looks to be a back-end issue, so may need some assistance!
