### ISSUE TITLE
normalize-space() function requires newer pyxform

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2864]
In short: support for `normalize-space` will be added by #2605

## Description

`normalize-space()` function _(returns a string with normalized whitespace by stripping leading and trailing whitespace of string and replacing sequences of whitespace characters with a single space)_ as outlined **[here](https://docs.getodk.org/form-operators-functions/#normalize-space)** not working as it should in KoBoToolbox. Users are able to upload an xlsform with this function in the KoBoToolbox server but are not able to deploy the same. They see an error message (as shown in the steps below) while deploying the same.

## Steps to Reproduce

1. Upload the xlsform with `normalize-space()` function. For ease, you could also use the following xlsform:
[normalize-space.xlsx](https://github.com/kobotoolbox/kpi/files/5492775/normalize-space.xlsx)
2. Deploy the xlsform with the `normalize-space()` function shared above.
3. You should see an error message as shown below:
![Image 2](https://user-images.githubusercontent.com/50188479/98213194-ce1f0300-1f6c-11eb-9602-92b0c3563348.png)

## Expected behavior 

The same xlsform with the `normalize-space()` function can be smoothly uploaded **[here](https://getodk.org/xlsform/)** but cannot be deployed in through KoBoToolbox.

## Actual behavior 

`normalize-space()` function not working as it should in KoBoToolbox.

## Additional details

**Link to the community forum:** https://community.kobotoolbox.org/t/cant-deploy-forms-using-normalize-space/13517

**Comment by jnm** [comment]
Pretty much all issues that take the the form of "I can't use XLSForm / XForm feature ___ in KoBo but I can use it in ODK ___," like this one, boil down to a difference in pyxform versions. Often times, we can figure out which pyxform version is required by looking at https://github.com/XLSForm/pyxform/blob/master/CHANGES.txt. In this case, however, it's not so straightforward: there's no mention of `normalize-space` anywhere in pyxform, so I:
1. Looked at forum.getodk.org and found https://forum.getodk.org/t/odk-xforms-spec-proposal-add-normalize-space-xpath-2-0-function/20990
1. Saw a reference there to https://github.com/getodk/javarosa/issues/460
1. Figured out that the earliest version of javarosa containing `normalize-space` is 2.15.0, per https://github.com/getodk/javarosa/commit/15972e00acc191abd0ec7762f3ee8b93d54d4f2c
1. Searched within pyxform to find where it specifies which version of javarosa is used
1. Found that it does not specify a version of javarosa directly, but rather a version of ODK Validate: https://github.com/XLSForm/pyxform/commits/181f792b8aeead2bac69f6287152f6c8880085d0/pyxform/validators/odk_validate/bin/installed.json
1. Found where ODK Validate pins the javarosa version: https://github.com/getodk/validate/commits/master/build.gradle
1. Found that ODK Validate 1.13.0 is needed to pull javarosa 2.15.0: https://github.com/getodk/validate/commit/840a47dc9418d0f36ed2261ff82b4274e4daa26f
1. Returned to pyxform and found that version 0.15.0 contains the upgrade to ODK Validate 1.13: https://github.com/XLSForm/pyxform/commit/f3335730e9db08459f98822142d6079632f64dc7

**Therefore,** this will be resolved when https://github.com/kobotoolbox/kpi/issues/2605 is completed. I'm in favor of keeping this issue open for reference instead of closing it as a duplicate, especially given that tracking down the specific pyxform version needed for `normalize-space` is quite a bit of work.

**Comment by jnm** [comment]
Please reopen if this does not work as expected.
