### ISSUE TITLE
Design UX for duplicating a submission

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2895]
Continuing the discussion at https://github.com/kobotoolbox/kpi/issues/2769#issuecomment-702881328, after talking with Tino:
1. This is a power-user feature that we don't need to advertise too much; it probably doesn't merit the prominence of a button next to view and edit on the left side of the table view;
1. It's totally fine if people have to view (click the eyeball for) a submission before they can access the duplication feature;
1. We ought to ask for confirmation somehow before performing the duplication—doing it accidentally is not nearly as bad as an accidental deletion, but it does compromise the integrity of the data;
1. The original UNHCR description seems to specify that the duplicate action should go directly to an Enketo edit screen; should we do that?
    * I don't think time constraints will allow us to develop the intermediary question-picker screen for the initial release, but
    * …we could show the regular single-submission view after duplication completes, and if no further editing is needed, the user could wander away. If they do need to edit, then they could click the existing edit button.

Nomenclature: is it better (consistency) to use "clone" since we already have a feature to "clone" projects and library items? Or would it reduce confusion to call this something else, like "duplicate"?

The whole business may be pretty bare-bones, at least initially, but we can chat about it when we meet on Monday :)

**Comment by Ig-Rebollo** [comment]
Some initial thoughts:

1. If we use 'clone' for a different feature, I would avoid reusing it. Duplication sounds better to me, specially if the intention is to edit its content afterwards so the two instances are ultimately not identical.
2. Editing after duplicating with the current in-table edit button should be ok, but in that case we should provide some clue indicating which item/row is the duplication. (maybe a small icon? maybe it gets highlighted somehow?)
3. Is it worth exploring the idea of providing the option to edit (or choosing) some minor things (or metadata) in the confirmation window? i.e. what date should the duplication display, the date of duplication or the date from the original item that was duplicated.

**Comment by jnm** [comment]
Notes from yesterday's call:

1. "Duplicate" action will definitely be available from the single-submission view modal. We haven't ruled out making it also available from the table view
1. Regardless of where "Duplicate" is invoked, a modal (mostly the same as the single-submission view) will appear to display the new, duplicate submission
1. This modal will present three actions (wording TBD; Ignacio is making a mockup):
   1. OK, which dismisses the modal, leaving a clone with only the IDs and timestamps changed
   1. Edit, which opens Enketo for further editing of the clone
   1. Discard, which deletes the clone (at this point, the clone already exists in the database)

@Ig-Rebollo, @duvld, please chime in if anything is missing.

**Comment by Ig-Rebollo** [comment]
@jnm @duvld @magicznyleszek 

Here are the mockups from the notes above:
![Attach-files-info](https://user-images.githubusercontent.com/22472326/100393448-aa009000-3007-11eb-96b4-d2402e51806f.jpg)
![Attach-files-info-1](https://user-images.githubusercontent.com/22472326/100393454-aec54400-3007-11eb-9f25-ac03cdb7c222.jpg)

One question I've been wondering about for a while is whether we want to take users back to the table view once they complete a duplication or back to the single-submission view modal. The natural behaviour would be going back to the table view, but can you think of any instance in which going back to the modal could be useful? Is it an option worth allowing?

cc @tinok

**Comment by tinok** [comment]
This looks great @Ig-Rebollo. My feeling is that staying on the single submission screen would make most sense, as you kind of implied. As a user, I found it confusing that after the duplicate was created I didn't have access to the same functionality as for the original record (I presumably would have to click 'Done', which feels like closing the modal altogether. My question is whether it shouldn't look more similar to the regular view, i.e.:

* the X button to close the modal
* saying 'Submission record (3 / 18)' in the top header
* moving the 'Duplicate created' together with the paragraph text and making it more of a notice message (some color/border?
* Same buttons for Edit / duplicate/ print / delete as usual (since otherwise I'd have to close the view and open it again from the table if I want to print it / make another duplicate). Same as above, I found it confusing that the button for Discard and Delete are different.

**Comment by Ig-Rebollo** [comment]
@tinok thanks for the feedback, those are all great points. We actually thought of a similar flow in our call, however the main challenge we noticed is that when duplicating a record there is no guarantee that the new record would be as you said '3 of 19'. Depending on how the table is displaying the rows, the new item might be '1 of 19' or '19 of 19', so _not next to the item I duplicated_. For instance, if the table is ordered by submission date, the duplication would become the most recent item, and therefore either first or last depending on the sorting. It felt that this might be quite confusing to users, so we decided to go on a different direction. 

Happy to hear your thoughts on this though. I do think making the two modals the same is actually better, as long as it is clear what happened.

@jnm @duvld please feel free to correct me if I got any of that wrong.

**Comment by jnm** [comment]
Sorry for brevity:

* "X button" seems to imply a dismissal—might lead people to believe they were aborting the duplication when in fact it had already happened. "Done" (in theory!) better conveys that the new submission has already been made. Same reason for having "discard" instead of "delete"; additionally, "discard" is not planned to present any scary warnings like "delete" does.
* Losing "Submission record (3 / 18)" and next/previous buttons kind of stinks but making it work sensibly is fairly complex as Ignacio described.
* I don't have an opinion about where "Duplicate created" is placed
* Is there a use case for:
  * Duplicating a duplicate (without editing it first?)
  * Printing a non-edited duplicate? (Why not print the original?)
  Maybe armchair UX on my part, but we're trying to convey that something meaningful has happened: wake up, you've duplicated a submission, and now there's junk in your data set unless you edit (to make the duplicate meaningful) or change your mind and discard it (like you discard a draft submission or a draft email). The third action, "done," gets de-emphasized because it's not understood to be commonly beneficial: UNHCR didn't ask for it, and I can't really think of how it would be used—but my imagination is quite limited :wink:

@duvld is in charge of #2896 now and is going to start building what's shown in the mockups. I don't foresee a technical difficulty in bringing back edit/duplicate/print/delete, or even validate, actions if that's preferable. It may even be faster to reuse more of the existing modal.

**Comment by tinok** [comment]
> Maybe armchair UX on my part, but we're trying to convey that something meaningful has happened: wake up, you've duplicated a submission, and now there's junk in your data set unless you edit (to make the duplicate meaningful) or change your mind and discard it (like you discard a draft submission or a draft email).

I agree with this, but that's what I'm trying to say in fact: The current design of the modal _after_ the duplication looks just like the one before, so either it should really have all the same functionalities or look and feel very different. When I looked it at (and again based on the current version from @duvld) I feel confused because it looks similar but works different.

> Is there a use case for:
> Duplicating a duplicate (without editing it first?)

Sure - if you've registered a hospital which you later want to split into different wards / satellite sites. 

> Printing a non-edited duplicate? (Why not print the original?)

Who knows, but why make a user first close the modal, find the record on the table, then print it from there?

I think the underlying question is, what happens when you click "DONE"? Do you close the modal and return to the table (my assumption)? --OR do you close the _duplication_ modal and return to the single submission view of the newly created record? If it's the latter then there's no need to change the buttons since it'll be possible to get to the regular functionalities that way.

**Comment by Ig-Rebollo** [comment]
> OR do you close the duplication modal and return to the single submission view of the newly created record? If it's the latter then there's no need to change the buttons since it'll be possible to get to the regular functionalities that way.

This was my original assumption, that why in the first mockup I had the 'done' as a button below, not where the 'X' would've been. Clicking on 'done' would've taken you back to the original submission. In that context, 'printing' and 'duplicate' don't make as much sense in the duplicated submission view.

Now, that's not the direction we took in the end. Given where the 'done' is now, it feels more natural that it closes the window and takes you back to the table view. In that case, there might be a stronger argument for keeping all the functionalities (print, duplicate, etc.) in the duplicated submission view as well.

Copying here what I wrote in Zulip to make what we have more intuitive:

1. Make the 'Duplicate created' draw more attention. Maybe where it says 'Duplicate created' we change it to simply 'Duplication sucessful' and we make the 'Duplicate created!' be a big heading just on top of the description text, in bold and blue colour.
2. Replace the 'duplicate' button in the duplicated submission window for a discard button that effectively deletes the duplication you just created.
3. Ignacio Rebollo:
4. (we did not discuss this one) but maybe creating a new validation status called 'duplication' that becomes the default status of a duplicated submission unless you change it? (It's a bit of a hack solution but maybe could be a quick fix to identify these submissions for the time being...)

**Comment by jnm** [comment]
I think we incorporated this feedback(?) @Ig-Rebollo, feel free to reopen if what we deployed still needs tweaking.

**Comment by Ig-Rebollo** [comment]
@jnm @magicznyleszek There are a few improvements that could be made. I think we discussed some of them last time but decided that we would have to leave them for a later occasion (which is fine). Not sure if you want to keep the issue open with these items, or if it is better to create a different issue altogether (maybe something to include in the wish list for example). The main points are:

1. When I click on 'duplicate' the modal disappears first, and then comes up again with the "Success" and "Duplicate created" message. Ideally, it would be nice to have a smoother transition (i.e. one modal slides into the other).
2. Buttons have no hierarchy (they are all the blue button that pops up so much). Ideally, in screens with several buttons, we want to shift towards outline buttons so each of them doesn't draw so much attention and we can establish a hierarchy. Buttons with a full colour should ideally be restricted to one per view/page (the most important action, for instance, the 'NEW' button in the left side menu)
3. Once I duplicate an item and I click on 'Edit', in the Enketo view, I have to click 'Submit' again. This is confusing as it makes me think I'm creating a whole additional copy, instead of editing the copy I made. Ideally we want to replace the 'Submit' for an 'Accept' or 'Update' in this context.
4. When you duplicate you get the standard dark notification message on the bottom left corner saying 'duplicate created', but you are already seeing that information in the new modal, so it feels a bit of an unnecessary repetition. I didn't notice this at the time (my bad), maybe it is not a big deal but it is something to think about moving forward. What information should go in the notifications and what information is better to display in the modals (this is more a reminder to myself).
