### ISSUE TITLE
Displaying XML Values in table view for select_one/multiple questions gives blank labels in dropdown

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3063]
## Description

Displaying XML Values in table view for select_one/multiple questions gives blank labels in dropdown

## Steps to Reproduce

1. Have form with `select_one` question and some submissions
2. Go to table view and in settings select "XML Values" in "Display labels or XML values?"
3. Observe that the table header filter for `select_one` question gives blank options

**Comment by Kalyan-Lama** [comment]
Community: https://community.kobotoolbox.org/t/while-viewing-kobo-forms-in-xml-values-format-data-in-drop-down-options-of-headings-are-not-visible/16742

**Comment by sebmercier** [comment]
@JacquelineMorrissette who added the "check-if-stale" label: Definitely not stale (if I correctly understand what this label means). This bug is still present on the KoboToolbox "Table" interface. Contrary to what some people mentioned in [this thread](https://community.kobotoolbox.org/t/table-view-filter-choices-not-showing/16410), the problem on our account (humanitarian server) seems to occur for all projects I've checked (I sampled about a dozen), even those with only a handful of submissions, and regardless of whether they are shared or not.

Could some developer please address this issue? It would be very much appreciated. I must do some bulk substitutions of select_one answers in one of our projects and doing so with XML values instead of labels would really be the less tedious option (providing I can select and filter the XML values, of course! :-))

**Comment by magicznyleszek** [comment]
I think this is a duplicate of #4412 (or rather the other way round). #4412 got fixed by #4662 in October :) To be precise, fix got merged on Oct 4, so it might ended up on production somewhere at the start of November.
