### ISSUE TITLE
Delete entire group functionality

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3132]
## Description

We need a way for users to delete the whole group with all inside. So when clicking the delete (trash bin) button we get something like that:

<img width="570" alt="Screenshot 2021-04-14 at 21 52 05" src="https://user-images.githubusercontent.com/2521888/114780660-9adc6d80-9d6f-11eb-92b7-3f27c19e11f8.png">

## Additional details

Needed for #3082

**Comment by Ig-Rebollo** [comment]
@magicznyleszek @tinok Two parts to this:

1. The best way to do this would be to simply have a button to split the group, different from the delete button. So, instead of just settings and delete, you would have settings, delete, and split group. 
![image](https://user-images.githubusercontent.com/22472326/115070117-8066d900-9ec2-11eb-8bdb-c0b001879b3c.png)
The split group icon could be done with a variation of the group icon on the navigation bar
![image](https://user-images.githubusercontent.com/22472326/115070213-a1c7c500-9ec2-11eb-90ba-ea576160cbe0.png)
Unfortunately with the current layout, an additional icon would make the space increase in height, which would look strange and make the form longer, so it is better not to do this. Ideally, we will want to do it this way only when we redesign the form builder, as I plan to lay out the question action icons horizontally instead of vertically. For the time being, it is better to go with the modal approach.

2. For the current modal, I feel we either don't need the 'delete' or the 'X' on the top right corner. Having both is a bit redundant. Also I would try to be clearer in each button. Instead of 'split' and 'delete' might be better to have 'ungroup questions' and 'delete everything'
![image](https://user-images.githubusercontent.com/22472326/115071568-675f2780-9ec4-11eb-9d96-3eb1f408d961.png)

**Comment by magicznyleszek** [comment]
Using modal would also be preferable in current Form Builder, because users are accustomed to having the split functionality under the "trash bin" icon.

I am working on it already :)

**Comment by Ig-Rebollo** [comment]
Great! Thanks @magicznyleszek here is the icon in svg
[ungroup-icon.svg.zip](https://github.com/kobotoolbox/kpi/files/6327467/ungroup-icon.svg.zip)
