### ISSUE TITLE
Hooks API improvements: filter and force retry

### ISSUE THREAD

**Issue by Yann-J** [kobotoolbox/kpi#3536]
## Description

Hello 👋

Recently we've been trying to make our REST Service exports more robust than the default retry behaviour - which already works pretty well but sometimes we need a more specific logic.

For this to work we figured we might need the following 2, seemingly fairly achievable improvements to the `hooks` API - which might lay down some work for future UI improvements for the management of REST failures:

* Support a status filter in the `GET /api/v2/assets/{asset_uid}/hooks/{hook_uid}/logs/` API - for instance `?status=0` (for failures) so that we only list the failed REST hook notifications. I'm no Django expert but looking at https://github.com/kobotoolbox/kpi/blob/master/kobo/apps/hook/views/v2/hook_log.py#L74 I think it might only a matter of adding a filter predicate here...
* Support a `force` parameter to force a retry in the `PATCH /api/v2/assets/{asset_uid}/hooks/{hook_uid}/logs/{uid}/retry/` API. It makes sense that automatic retries would be capped to 3, but it would be nice if it was possible to also override this limit to force retries through the API (or maybe at some point, manually in the UI). This might be trickier as I'm not sure about the back-end validations enforcing the max attempts... Maybe it's only a matter of overriding this condition in the API code: https://github.com/kobotoolbox/kpi/blob/master/kobo/apps/hook/views/v2/hook_log.py#L96

Hope these suggestions make sense!

I am not certain if I can propose a PR for it myself, as I don't have much Django background... but I could give a try.

**Comment by noliveleger** [comment]
Hello @Yann-J, 
Thank you for your idea. Unfortunately, we are a small team, we cannot focus on such requests as fast as we would want. 
I don't think we will be able to address this on a short/mid term.

Your first point would be easily feasible. Maybe a filter back-end class would be better, (see Django Rest Framework mechanism).

For, the second point, as you said, this might be trickier because the task may have been already rescheduled in Celery. It has to be cancelled when force retry is triggered. 
Moreover, the force retry must be throttled. We don't want users to retry many times in a row.

So, yes, you could it a try for sure and any help would be appreciated.

**Comment by Yann-J** [comment]
OK, just gave it a try in #3595 - just covering the `status` filter parameter. Successfully tested on my side.

After some more fiddling I actually realize that the second point is not necessary, since it appears that's already the current behavior: calls to the `retry` API will go through even when the max automatic attempts is reached - in fact it will ONLY go through when the max attempts are reached (`status = HOOK_LOG_FAILED`)... I'm not sure why I thought it wasn't the case.

This means that with this PR in, we will be able to implement third-party retry triggers (look for failed hooks, then retry one by one).

**Comment by noliveleger** [comment]
@Yann-J, sorry for the delay. 
We can't accept your PR the way it is. Let me update the PR itself
