### ISSUE TITLE
Upgrade pyxform to `v1.9.0`

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3686]
https://github.com/XLSForm/pyxform/releases/tag/v1.9.0

**Comment by jnm** [comment]
XLSForm/pyxform#575 now requires `xlrd==2.0.1`, which refuses to open XLSX files. This means we have to rework all of our Excel reading code—here, in kobocat, and in formpack—because our older, XLSX-capable xlrd dependency will clash with pyxform's—and, obviously, we need pyxform.

This issue is already causing unit tests in formpack [to fail](https://github.com/kobotoolbox/formpack/runs/5314589560?check_suite_focus=true) with `xlrd.biffh.XLRDError: Excel xlsx file; not supported`, because formpack follows the Python convention of not pinning dependency versions in libraries. We *could* pin dependency versions for the CI environment, but it's just postponing the inevitable: the old xlrd [doesn't work](https://github.com/XLSForm/pyxform/issues/501#issuecomment-956870899) with Python 3.9.

**Comment by joshuaberetta** [comment]
Thanks @jnm!
