### ISSUE TITLE
Bug: including two links in a question breaks both.

### ISSUE THREAD

**Issue by DerekCaelin** [kobotoolbox/kpi#3698]
## Description

I've used markdown to insert hyperlinks into a form: https://ee.kobotoolbox.org/x/0Fcn6Bns. When I include more than one link, the urls change and are broken:

Example: 

`Design businesses & projects, [incubate](https://docs.google.com/document/d/1HbM-wzFc5HiDzhWlBjzfv7hZNLoCJm8f_3hCote2mKY/edit#heading=h.u1w3x0wpdhd3) or [scale](https://docs.google.com/document/d/1HbM-wzFc5HiDzhWlBjzfv7hZNLoCJm8f_3hCote2mKY/edit#heading=h.tsvk905dwdeb) of key component landscape investments`

the first hyperlink becomes (note the `<em>` insertion): 

`https://docs.google.com/document/d/1HbM-wzFc5HiDzhWlBjzfv7hZNLoCJm8fM<em>3hCote2mKY/edit#heading=h.u1w3x0wpdhd3`

## Steps to Reproduce

1. Write a question and insert two hyperlinks using markdown

## Expected behavior 

Link to a google doc

## Actual behavior 

Link breaks, and the website does not load.

**Comment by jnm** [comment]
I think the issue here is that whatever Markdown parser Enketo is using treats everything between underscores as text that should be italicized, despite the underscores being inside a hyperlink URL. There has to be a pair of underscores to trigger this behavior, so you didn't see it with only one of your Google Doc links.

When trying this simple form on https://getodk.org/xlsform/, which is running Enketo 3.1.0:
type | name | label
-- | -- | --
`note` | `underscore_link` | `[i like underscores](https://fun.stuff/great_job_excellent)`

…it renders as
```html
<a href="https://fun.stuff/great%3Cem%3Ejob%3C/em%3Eexcellent" rel="noopener" target="_blank">i like underscores</a>
```

**Comment by jnm** [comment]
@DerekCaelin you should be able to work around this issue by placing a backslash before each underscore in your URLs (see discussion at linked Enketo issue). Thanks for your patience.

**Comment by DerekCaelin** [comment]
Perfect! thanks.

Derek Caelin
Social Impact Technologist
Connect with me on [Mastodon](https://sunbeam.city/web/accounts/107652396454526999) and [Twitter](https://twitter.com/derekcaelin)

------- Original Message -------
