### ISSUE TITLE
CI build runs slow due to redis and more

### ISSUE THREAD

**Issue by bufke** [kobotoolbox/kpi#3820]
## Description

Building the kpi docker image takes about 14 minutes. It contains references to redis

`ERROR:celery.backends.redis:Connection to Redis lost: Retry (4/20) in 1.00 second.`

Redis isn't needed to build the docker image. It may be worth reviewing the build process more generally. It should not attempt to make service connections outside of the pypi and apt repos.

## Steps to Reproduce

https://gitlab.com/kobo_toolbox/kpi/-/jobs/2500185890

**Comment by jnm** [comment]
So we're killing off #3440 to get rid of the Redis annoyance. I would object, but no one seems to use the runtime-configurable autoscale feature. It was built for UNHCR and they don't use it; just recently on OCHA, even I forgot about it when dealing with exactly the situation it was designed for.

I think it's worth noting that when #3440 was made, it did not cause 40 seconds of wasted time during the CI build process. I'm not sure what has changed since then, but it doesn't feel like the last time we'll ever grapple with Python code trying to access a database when none is available. It's a fair point, though, that Django [discourages](https://docs.djangoproject.com/en/3.2/ref/applications/#django.apps.AppConfig.ready) talking to databases in `AppConfig.ready()`, and #3440 did that.

I find #3863 dissatisfying because, while it cuts off a sore thumb, it does not address the overall issues mentioned in this issue. We should answer these questions:
1. Do we ever need to run management commands or other application code in "non-runtime" environments like the Docker build process?
1. If so, how do we distinguish between runtime and non-runtime?

Some further thoughts:
1. Would it be better to avoid the the management commands in our current `Dockerfile` altogether?
    1. Django [itself](https://code.djangoproject.com/ticket/23321) stores `.mo` files [in git](https://github.com/django/django/blob/main/django/conf/locale/ca/LC_MESSAGES/django.mo). We could do that too and get rid of `compilemessages` as a build step.
    1. Could `collectstatic` be invoked at runtime and put its junk directly in the proper place, instead of having it deposit files in one location that then has to be [`rsync`ed to the volume](https://github.com/kobotoolbox/kpi/blob/602094b75984572a23a46ba8a90f96683ec5e076/docker/init.bash#L65-L66) that's shared with the nginx container?
1. Is it really useful to have defaults for database URLs? It's hard to imagine these existing for any reason other than to be overwritten, especially when we bizarrely have both `localhost` and `redis_cache` in the Redis defaults:
    ```
    kpi$ grep 'redis://' kobo/settings/base.py
    CELERY_BROKER_URL = os.environ.get('KPI_BROKER_URL', 'redis://localhost:6379/1')
    'REDIS_SESSION_URL', default='redis://redis_cache:6380/2'
    'default': env.cache(default='redis://redis_cache:6380/3'),
    ```
    1. The non-localhost hostnames look like they were set to match kobo-docker service names. If kobo-docker really depends on the default values, which [I doubt](https://github.com/kobotoolbox/kobo-docker/blob/aee0ecfd5005cf2c666c35afac1ca3075c328506/env/envfiles/databases.txt), then let kobo-docker handle setting the environment variables appropriately.
    1. Removing the defaults would make it efficient to tell when the databases are not accessible, but that wouldn't differentiate between configuration errors and "non-runtime" mode.

**Comment by bufke** [comment]
I'm for merging #3863 but I did offer a less disruptive alternative if you'd rather wait. I think it's is a step in the direction I'd like to see.

1 and 2 -  I think it's fine to run management commands at build time, such as collectstatic (assuming the target is a local file system). I don't believe we should depend on external resources at build time (nor app startup) except for pypi, npm, and docker registries that are explicitly build time resources. That's the distinction.

Further thought 1) compilemessages has lead to some "why does my build not work today" issues seen on internal chat when something is wrong with translations. I'd rather see this done in a CI bot or manually on some schedule. Storing the mo file in git is fine. It's storing a snapshot of the translations at a point in time. Maybe it's not perfectly normalized as it's really a computed value, but it's good enough and the mo files do have unique meaning in that they are known to be working translations. 

I don't love the usage of rsync (or chmod) that doubles file sizes and slows Docker builds. I think there is a way we could remove this but I would need to consider how to do so without breaking existing desired behavior.

2) We could align the python defaults to docker compose defaults. That would greatly simplify kobo-docker compose files, maybe to the point where it's 50 lines of yaml and for developers, absolutely 0 configuration. `docker compose up` and that's it. Minimal for vanilla looking end users (Django secret key, etc still get defined). Of course that isn't the reality today and the real answer is - I'm used to working in this zero-conf manner and so I write defaults without thinking about it.

Zero conf set ups are far beyond the scope of "speed up docker builds" but I'd love to discuss more on video chat sometime.
