### ISSUE TITLE
[NLP] Random 502s when changing submission or question in processing UI

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3823]
## Description

When I [Tino] switch between questions or submissions I randomly get a 502 response (UI shows "Failed to get processing data"), but it's not consistent (not the same question or same submission).

~~Could it be that if a user views the submission / response pair for the first time the backend needs to create the processing fields first, which leads to the 502 as they are not yet available upon first request sometimes?~~ Never mind, I was able to reproduce it even after viewing the same submission / response pair again, it seems to be random when this does/does not happen.

https://user-images.githubusercontent.com/2521888/170135055-666838bd-056e-4109-b001-1a6abc633824.mov

## Additional details

From Zulip conversation near https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/NLP/near/115173

**Comment by jnm** [comment]
The dev server shown here has pretty limited resources, and the processing UI loads the entire audio file every time (and immediately).

I cannot reproduce the issue right now. I'm on the same dev server but with much newer code. If this is still a problem, though, a few options come to mind:
* Simply remove the audio player (temporarily) and see if Tino can still reproduce the 502s
* Stop preloading, like what we did in the table view: 5aa18ef23699fc4ce3dc07d9ac4b2cdfccc8dd83
* Debounce audio attachment loading so that fast navigation doesn't trigger so much traffic

**Comment by JacquelineMorrissette** [comment]
Closing, unable to reproduce. We can reopen this if it comes back
