### ISSUE TITLE
Kobo Collect, Survey are directly going to "Delete Saved forms"

### ISSUE THREAD

**Issue by Pkumar22in** [kobotoolbox/kpi#3829]
I am using a self hosted KoboToolBox Platform, recently we upgraded our KoboCollect version to latest one, Since then I see a huge number of people have started reporting that When the forms were submitted, rather than being moved to 'View Sent Form' (as should happen) or 'Edit Saved Form' (as happens when there is no network and a form is submitted). Instead it goes straight to 'delete saved form'. You can view that the form is there, but cannot take any action (i.e. restore it, submit it, etc.). The data is not submitted when this occurs. 

can any one have a look at it please or guide me how to solve this?

**Comment by jnm** [comment]
@Pkumar22in, please request support here: https://community.kobotoolbox.org/c/kobo-users/14. This issue tracker is only for software development tasks, and if this does prove to be a bug with Collect, then it will need to be reported in another repository with much more detail so that the developers can identify the cause. We have staff on the community.kobotoolbox.org forum (and very many experienced users) who can help you solve this.

FYI, this is not correct:
> 'Edit Saved Form' (as happens when there is no network and a form is submitted)

When there is no network connection, the form should go into "Send Finalized Form". What you see in "Edit Saved Form" should only be _drafts_, i.e. submissions where the "Mark form as finalized" box was **UN**checked when someone got to the end and clicked "Save Form and Exit". Those drafts also appear in "Delete Saved Form".
