### ISSUE TITLE
Data Exportation never ends

### ISSUE THREAD

**Issue by hsinbennour** [kobotoolbox/kpi#3949]
## Description

We can't get  the data when exported as excel from the website(manually or through R), it says processing but it never finishes preparing the data for downloading. This was flagged by other colleagues in different locations using different servers.

**Comment by jnm** [comment]
Hi, if you're hosting your own server, please post a message here: https://community.kobotoolbox.org/c/kobo-install/18
If you are using one of our public instances, please post a message here: https://community.kobotoolbox.org/c/kobo-users/14

These features work for many users on many instances, and without more technical detail, we cannot reproduce the problem. Therefore, this needs to go through our support system so that we can ascertain whether it is a bug requiring a code change (in which case we would reopen this issue with more detail) or a configuration error. Thanks.
