### ISSUE TITLE
Refactor modal dialog system

### ISSUE THREAD

**Issue by p2edwards** [kobotoolbox/kpi#3977]
## Description

Refactor modal dialog system, dropping alertify.dialog.

We probably want:

- New styles from #3643
- Better behavior for nested modals
  - e.g. `'Esc'` should close one popup at a time
- Use typescript, mobx, for new or rewritten components

Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI

## Related Issues

Implement #3643 - Component design for modals
Also part of #3837 - replace/drop Alertify

Follow-up to PR https://github.com/kobotoolbox/kpi/pull/3972#discussion_r949377341 
> `// TODO: port from alertify.dialog to new modal system`

**Comment by magicznyleszek** [comment]
Some notes:
- it would be useful to check if we can refactor `jsapp/js/components/common/modal.es6` to be a useful "base" component, instead of deprecating it and writing a component from scratch
- looking at specs, some configuration would be needed:
  - size: `standard` and `large`
  - title with:
    - optional left side icon
    - optional "x" close button
    - name (mostly a `string`, but should work with HTML content)
  - closing by outside click is optional (enabled by default)
  - closing by esc key is optional (enabled by default)
- other requirements:
  - we need a way to programatically open (and close) a modal (i.e. call a function)
  - we need a way to know if a modal is open
  - the above suggest we need a uid for modals (`utils.ts` have `generateUid` function that would be good enough, opening a modal should assing uid to id and return it)
  - some min/max sizes (see [Figma file](https://www.figma.com/file/Q04O151tZ2r4ObqL860Nqu/KoboToolbox-Design-System-2.0?node-id=874%3A539))
  - header will always be there (TBD?)
  - content below header can take whole available area (e.g. a video modal)
  - footer is optional, and should probably allow any content, but with suggestion to use predefined simple bem components:
    - footer wrapper
    - footer left, center, and right containers (all optional) - so we can put buttons inside of these

**Comment by magicznyleszek** [comment]
Another note: besides those custom modals we have, we also need to create a prompt modal that will be using the base conponent(?)
