### ISSUE TITLE
Allow username that contains dots

### ISSUE THREAD

**Issue by fgomezdev** [kobotoolbox/kpi#4139]
## Description
It is necessary to be able to use usernames that contain dots for cases of login integration with LDAP or social networks.
Currently, this is only possible from the admin interface but this causes problems when the user wants to deploy forms.

`ideas` `enhancement`

## Steps to Reproduce

1. Create a new user with a username containing a dot for example **test.user**
2. Create or upload a form and try to implement it

## Expected behavior 
Being able to implement it successfully

## Actual behavior 
Confirming the implementation of the form keeps it busy until it gives an error after a while
(This was tested on different kobo implementations, always with the same behavior)

## Additional details
One way to fix this is to modify /kpi/kpi/views/v2/user.py:

```
class UserViewSet(viewsets.GenericViewSet, mixins.RetrieveModelMixin):
   queryset = User.objects.all()
   serializer_class = UserSerializer
   lookup_field = "username"
 
   lookup_value_regex = "[^/]+"   # < --- this fixes the problem of deploying forms when the username contains dots

```

(Sorry for my bad English)

**Comment by jnm** [comment]
Hello! Thanks for your report (and I think your English is great).

I'm pretty reluctant to allow more characters in usernames because it will require an unknown amount of changes to our legacy [kobocat](https://github.com/kobotoolbox/kobocat) application, and I don't want to find out that we've missed some necessary change once somebody working on an important humanitarian project is midway through a large data-collection effort.

I hear you about "login integration with LDAP or social networks", but we've recently integrated django-allauth in order to allow single sign-on with a variety of providers. The username stored in Django no longer needs to match the username used by an external service. Do you think this could solve the problem for you? Details are in #4163

**Comment by jnm** [comment]
Sorry; we have decided not to support usernames with dots and rather to begin enforcing our username requirements in the Django admin interface: https://github.com/kobotoolbox/kpi/pull/428.

I hope the new django-allauth SSO support can help your use case. https://github.com/kobotoolbox/kpi/pull/4163
