### ISSUE TITLE
Allow making some actions in formbuilder with keyboard

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#553]
## Details

Allow navigating forms using keyboard only as much as possible - to improve accessibility and make usage faster by power users.

Important places:
- Form Builder: user can switch between input fields using the tab key and create a new question without using the mouse.

## Additional details

We need to remove global disabling of `:focus` styles - instead we can try using https://github.com/ten1seven/what-input or just enable them and make prettier than default.

**Comment by magicznyleszek** [comment]
There are multiple different inputs that user would select with keyboard, plus nested groups could require some more visuals - thus "needs-design" label :)

**Comment by tinok** [comment]
@magicznyleszek This is what we had in mind with this: 

![image](https://user-images.githubusercontent.com/673511/79349744-a00c9f80-7f04-11ea-97f0-b0fd19cb53ea.png)

![image](https://user-images.githubusercontent.com/673511/79349974-df3af080-7f04-11ea-87f7-3f48e5f630ea.png)

![image](https://user-images.githubusercontent.com/673511/79350123-0f828f00-7f05-11ea-91f4-0441f8c8c002.png)

**Comment by duvld** [comment]
Note: Adding keyboard actions to choices questions would currently most likely be made in `viewUtils.makeEditable` because of the way pressing "Enter" behaves with `makeEditable` (they have no input fields) 

Since we have an issue (https://github.com/kobotoolbox/kpi/issues/2152) to remove instances of `makeEditable` already, it is probably best to work off of the solution to that issue rather than doing the work twice

**Comment by magicznyleszek** [comment]
I feel that focus styles are good enough and all most needed keyboard navigation is covered. I am closing this, we can make some more advanced changes by creating a new issue :)
