### ISSUE TITLE
Default options can be replaced with single click

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#555]
User should be able to replace default option text without having to highlight or delete it (like placeholders)

**Comment by magicznyleszek** [comment]
I don't know if it would be easy to make it work like placeholder (i.e. detecting if it's default option, or written by user - because I think it's being stored in the same way), if not we could make the newly added option auto selected, so after clicking "+" user can start typing right away.

![kapture 2018-08-19 at 9 55 18](https://user-images.githubusercontent.com/2521888/44306806-587fea00-a396-11e8-973c-52007934d648.gif)

**Comment by duvld** [comment]
The changes needed for this seem to be similar to the code for https://github.com/kobotoolbox/kpi/commit/b596dd4746715f3de761fd620476f7ead6e81d9f - we can make style questions input fields as well - which would also allow tab navigation.
