### ISSUE TITLE
When cloning a question don't prompt for a title

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#663]
Library Questions don't have titles. So when a user clones an existing question they should not be prompted for a new title (as they are when cloning a block or form).

**Comment by magicznyleszek** [comment]
@tinok actually questions do have titles
<img width="253" alt="screenshot 2018-10-23 at 14 59 58" src="https://user-images.githubusercontent.com/2521888/47362324-6f172a00-d6d4-11e8-844a-55681260371f.png">
…and title is being displayed both in Library List:
<img width="615" alt="screenshot 2018-10-23 at 15 00 08" src="https://user-images.githubusercontent.com/2521888/47362325-6fafc080-d6d4-11e8-9240-3732bd89e543.png">
…and in Form Builder's "Add from Library":
<img width="368" alt="screenshot 2018-10-23 at 15 01 28" src="https://user-images.githubusercontent.com/2521888/47362367-89e99e80-d6d4-11e8-96eb-6380022dd83f.png">

**Comment by magicznyleszek** [comment]
@jnm what do you think?

**Comment by tinok** [comment]
@magicznyleszek I would say that they *shouldn't have titles* other than their actual default label. When a user adds a question they would refer to that question by its label, not some other text. It's redundant and too time consuming to add a manual title. 

So when creating a question, or cloning, the question label should equal the title. 

From my perspective as a user, the title (where normally we show the form / project / block title) could just be hidden.

**Comment by magicznyleszek** [comment]
@tinok actually it is almost done already - when you create a question and leave title empty, all the places in the app uses the name of question instead. So now it will only require to hide the title input if someone chooses `NEW -> Question` from the Library View or when editing a question.

**Comment by jnm** [comment]
Hi @tinok,

We don't ever really _have_ to prompt for a title when cloning any kind of asset, but the fact stands that `question`s can have titles, both by virtue of being valid XLSForm and because the KPI `Asset` model has a `name` field regardless of `asset_type`. I think it's very easy for a library `question` to end up having a title that's different from the label of its one and only question, and I don't want to arbitrate this by hard-coding assumptions about users' intent.

I can see that there's an annoying behavior when trying to clone a `question` that was never given a title, i.e.

1. I create a new `question`;
1. I enter the label "How happy are you?" for my question in the form builder;
1. I do _not_ add a title;
1. I save and close my `question`;
1. I see "How happy are you?" in the library list :heavy_check_mark: 
1. I see "Clone of untitled" when I try to clone this `question` :x: 
![image](https://user-images.githubusercontent.com/2085013/51810538-7d965400-2276-11e9-8b65-6484dcd6c474.png)

**I think that I should see "Clone of How happy are you?" instead**, but this doesn't address your original issue. Would you expect that cloning "How happy are you?" just makes another "How happy are you?" without prompting and without a prefix, or should it be called "Clone of How happy are you?"

## Background

Questions and blocks are fluid in their identity: I don't see any reason why a person should be prevented from adding a second or subsequent question to a library `question`—thus creating a `block`—or removing questions from a `block` until only one is left. The backend code accepts this flexibility by [inferring](https://github.com/kobotoolbox/kpi/blob/81096021377371959c90437be0c1fdbf2ffc595b/kpi/models/asset.py#L601-L607) whether `asset_type` should be `question` or `block` based on the number of questions. Additionally, when importing XLSForm, there aren't separate "upload question" and "upload block" features: there's a single library import, and it allows for a `title` on the `settings` sheet. To me, the `question`/`block` distinction is for the benefit of someone browsing a list view.

If we accept that `block`s should have titles and that `question`s can easily become blocks (and vice versa), then preventing `question`s from having titles (or forcing each title to equal the default label of the first and only question) becomes tricky.

**Comment by magicznyleszek** [comment]
@tinok ping :)

**Comment by joshuaberetta** [comment]
@jnm should we keep this issue open? Seems this hasn't really been a problem and the behaviour has changed a bit so that a clone of an untitled question no longer results in "Clone of Untitled".

**Comment by magicznyleszek** [comment]
I think that with #3410 the last issue is fixed. Closing this.
